# Generated by Django 6.0.7 on 2026-07-15 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Gestión fiscal')),
                ('estado', models.CharField(choices=[('preparacion', 'Preparación'), ('abierta', 'Abierta'), ('formulacion', 'Formulación'), ('revision', 'Revisión'), ('consolidacion', 'Consolidación'), ('aprobacion', 'Aprobación'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], default='preparacion', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('anio_inicio_plurianual', models.PositiveIntegerField(blank=True, help_text='Año inicial del horizonte plurianual', null=True)),
                ('anio_fin_plurianual', models.PositiveIntegerField(blank=True, help_text='Año final del horizonte plurianual', null=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión fiscal',
                'verbose_name_plural': 'Gestiones fiscales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='CicloFormulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('fecha_cierre_prorroga', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_formulacion', to='gestion.gestionfiscal')),
            ],
            options={
                'verbose_name': 'Ciclo de formulación',
                'verbose_name_plural': 'Ciclos de formulación',
                'ordering': ['gestion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFormulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='gestion.cicloformulacion')),
            ],
            options={
                'verbose_name': 'Etapa de formulación',
                'verbose_name_plural': 'Etapas de formulación',
                'ordering': ['ciclo', 'orden'],
                'unique_together': {('ciclo', 'codigo')},
            },
        ),
    ]
