# Generated by Django 6.0.7 on 2026-08-11 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionfiscal',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'Preparación'), ('abierta', 'Abierta'), ('formulacion', 'Formulación'), ('revision', 'Revisión'), ('consolidacion', 'Consolidación'), ('aprobacion', 'Aprobación'), ('vigente', 'Vigente'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada'), ('anulada', 'Anulada')], default='preparacion', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gestionfiscal',
            index=models.Index(fields=['estado'], name='gestion_ges_estado_537ec5_idx'),
        ),
    ]
