# Generated by Django 6.0.7 on 2026-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionfiscal',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'Preparación'), ('abierta', 'Abierta'), ('formulacion', 'Formulación'), ('revision', 'Revisión'), ('consolidacion', 'Consolidación'), ('aprobacion', 'Aprobación'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada'), ('CONFIGURACION', 'Configuración'), ('HABILITADA', 'Habilitada'), ('EN_FORMULACION', 'En formulación'), ('VIGENTE', 'Vigente'), ('CERRADA', 'Ciclo cerrado')], default='preparacion', max_length=20),
        ),
    ]
