# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_internal', models.BooleanField(default=True, verbose_name='Recibir notificaciones internas')),
                ('receive_email', models.BooleanField(default=False, verbose_name='Recibir notificaciones por correo')),
                ('frequency', models.CharField(choices=[('inmediata', 'Inmediata'), ('diaria', 'Diaria'), ('semanal', 'Semanal')], default='inmediata', max_length=10, verbose_name='Frecuencia de envío')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('template_subject', models.CharField(blank=True, help_text='Plantilla para el asunto del correo. Use {variable} para interpolación.', max_length=300, verbose_name='Asunto del template')),
                ('template_body', models.TextField(blank=True, help_text='Plantilla para el cuerpo del correo. Use {variable} para interpolación.', verbose_name='Cuerpo del template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de notificación',
                'verbose_name_plural': 'Tipos de notificación',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('entity_type', models.CharField(blank=True, help_text='Tipo de entidad relacionada (ej: gestion, indicador, tarea)', max_length=100, null=True, verbose_name='Tipo de entidad')),
                ('entity_id', models.UUIDField(blank=True, help_text='UUID del registro relacionado', null=True, verbose_name='ID de entidad')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión fiscal')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos adicionales')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.tiponotificacion', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificacio_user_id_4644a8_idx'), models.Index(fields=['user', '-created_at'], name='notificacio_user_id_f4d093_idx'), models.Index(fields=['gestion'], name='notificacio_gestion_0cdfd1_idx'), models.Index(fields=['priority'], name='notificacio_priorit_f9c091_idx')],
            },
        ),
    ]
