# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionFisicaFinanciera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('meta_fisica', models.CharField(blank=True, max_length=500)),
                ('unidad_medida', models.CharField(blank=True, max_length=100)),
                ('cantidad_programada', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('trimestre1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trimestre2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trimestre3', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('trimestre4', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programación física y financiera',
                'verbose_name_plural': 'Programaciones físicas y financieras',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionPlurianualProyecto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('monto_programado', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programación plurianual de proyecto',
                'verbose_name_plural': 'Programaciones plurianuales de proyectos',
                'ordering': ['proyecto', 'anio'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoInversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('codigo_sisin', models.CharField(blank=True, help_text='Código SISIN-WEB', max_length=100)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.PositiveSmallIntegerField(choices=[(1, 'Continuidad'), (2, 'Financiamiento asegurado'), (3, 'Nuevo estratégico'), (4, 'Otro nuevo')], default=4)),
                ('etapa', models.CharField(choices=[('preinversion', 'Preinversión'), ('inversion', 'Inversión'), ('cierre', 'Cierre'), ('operacion', 'Operación')], default='preinversion', max_length=20)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ejecucion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('gestion_inicio', models.PositiveIntegerField()),
                ('gestion_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_inversion', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_inversion', to='catalogos.organismofinanciador')),
            ],
            options={
                'verbose_name': 'Proyecto de inversión',
                'verbose_name_plural': 'Proyectos de inversión',
                'ordering': ['-gestion_inicio', 'prioridad', 'codigo_interno'],
            },
        ),
    ]
