# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('inversion', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinversion',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_inversion', to='presupuesto.programapresupuestario'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='catalogos.tipoproyecto'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_inversion', to='organizacion.unidadejecutora'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programacionplurianualproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion_plurianual', to='inversion.proyectoinversion'),
        ),
        migrations.AddField(
            model_name='programacionfisicafinanciera',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion_fisica_financiera', to='inversion.proyectoinversion'),
        ),
        migrations.AlterUniqueTogether(
            name='programacionplurianualproyecto',
            unique_together={('proyecto', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='programacionfisicafinanciera',
            unique_together={('proyecto', 'gestion')},
        ),
    ]
