# Generated by Django 6.0.7 on 2026-08-10 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0002_initial'),
        ('organizacion', '0001_initial'),
        ('poau', '0003_accioncortoplazo_operacion_actividad_and_more'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('codigo_sisin', models.CharField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('gestion', models.PositiveIntegerField()),
                ('fase', models.CharField(choices=[('idea', 'Idea / Demanda'), ('condiciones_previas', 'Condiciones previas'), ('preinversion', 'Preinversión'), ('formulacion', 'Formulación técnica'), ('costos', 'Costos y presupuesto'), ('revision', 'Revisión técnico-financiera-legal'), ('contratacion', 'Contratación'), ('ejecucion', 'Ejecución'), ('supervision', 'Supervisión / Fiscalización'), ('cierre', 'Recepción / Cierre'), ('evaluacion', 'Evaluación')], default='idea', max_length=30)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(default=4)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ejecucion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_v2', to='organizacion.unidadejecutora')),
            ],
            options={
                'verbose_name': 'Proyecto (SIS-PRO V2)',
                'verbose_name_plural': 'Proyectos (SIS-PRO V2)',
                'ordering': ['gestion', 'codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('idea', 'Ficha de idea'), ('itcp', 'ITCP'), ('edtp', 'EDTP'), ('expediente', 'Expediente de formulación'), ('contrato', 'Contrato'), ('acta', 'Acta de recepción'), ('evaluacion', 'Informe de evaluación'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tecnicos', to='inversion.proyecto')),
            ],
            options={
                'verbose_name': 'Documento técnico',
                'verbose_name_plural': 'Documentos técnicos',
                'ordering': ['proyecto', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostoProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('anio', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='inversion.proyecto')),
            ],
            options={
                'verbose_name': 'Costo de proyecto',
                'verbose_name_plural': 'Costos de proyecto',
                'ordering': ['proyecto', 'anio', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='CondicionPrevia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cumplida', models.BooleanField(default=False)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_previas', to='inversion.proyecto')),
            ],
            options={
                'verbose_name': 'Condición previa',
                'verbose_name_plural': 'Condiciones previas',
                'ordering': ['proyecto', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoTerritorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='territorio.localizacionterritorial')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorios', to='inversion.proyecto')),
            ],
            options={
                'verbose_name': 'Territorio de proyecto',
                'verbose_name_plural': 'Territorios de proyecto',
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'localizacion'), name='uniq_proyecto_localizacion')],
            },
        ),
        migrations.CreateModel(
            name='VinculoProyectoActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=True)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_vinculados', to='poau.actividad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_actividad', to='inversion.proyecto')),
            ],
            options={
                'verbose_name': 'Vínculo proyecto-actividad',
                'verbose_name_plural': 'Vínculos proyecto-actividad',
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'actividad'), name='uniq_vinculo_proyecto_actividad')],
            },
        ),
    ]
