# Generated by Django 6.0.7 on 2026-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0003_proyecto_documentotecnico_costoproyecto_and_more'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['gestion', 'fase'], name='inversion_p_gestion_54e0e7_idx'),
        ),
    ]
