# Generated by Django 6.0.7 on 2026-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0005_actividadtdr_alternativaproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_preinversion',
            field=models.CharField(choices=[('registrada', 'Iniciativa registrada'), ('en_admisibilidad', 'En admisibilidad'), ('admitida', 'Admitida'), ('itcp_elaboracion', 'ITCP en elaboración'), ('itcp_revision', 'ITCP en revisión'), ('itcp_aprobado', 'ITCP aprobado'), ('edtp_elaboracion', 'EDTP en elaboración'), ('edtp_revision', 'EDTP en revisión'), ('edtp_aprobado', 'EDTP aprobado'), ('viable', 'Viable'), ('habilitado_poa', 'Habilitado para programación'), ('enviado_poa', 'Enviado a SIS-POA'), ('no_viable', 'No viable'), ('archivado', 'Archivado')], default='registrada', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudreformulacion',
            name='sistema_origen',
            field=models.CharField(default='SIS-POA', max_length=50),
        ),
    ]
