# Generated by Django 6.0.7 on 2026-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0005_actividadtdr_alternativaproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionitcp',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='preinversion/condiciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='condicionitcp',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='condicionitcp',
            name='categoria',
            field=models.CharField(choices=[('justificacion', 'Justificación y alineamiento'), ('idea', 'Idea del proyecto'), ('compromiso_social', 'Compromiso social'), ('derecho_propietario', 'Derecho propietario'), ('terceros', 'Derechos de vía y terceros'), ('uso_suelo', 'Uso de suelo'), ('ambiente', 'Impactos ambientales'), ('riesgo', 'Riesgos y cambio climático'), ('otros', 'Otros aspectos'), ('conclusiones', 'Conclusiones y recomendaciones')], max_length=40),
        ),
    ]
