# Generated by Django 6.0.7 on 2026-08-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0006_condicionitcp_archivo_condicionitcp_nombre_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionitcp',
            name='categoria',
            field=models.CharField(choices=[('derecho_propietario', 'Derecho propietario'), ('uso_suelo', 'Compatibilidad de uso de suelo'), ('terceros', 'Derecho de vía / afectaciones'), ('riesgo', 'Riesgos no mitigables'), ('competencia_institucional', 'Competencia institucional')], max_length=40),
        ),
    ]
