# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('indicadores', '0002_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ue_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='organizacion.unidadejecutora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa presupuestario',
                'verbose_name_plural': 'Programas presupuestarios',
                'ordering': ['gestion', 'codigo'],
                'unique_together': {('codigo', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('gestion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='presupuesto.programapresupuestario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto presupuestario',
                'verbose_name_plural': 'Proyectos presupuestarios',
                'ordering': ['programa', 'codigo'],
                'unique_together': {('codigo', 'programa', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='ActividadPresupuestaria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('gestion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='presupuesto.proyectopresupuestario')),
            ],
            options={
                'verbose_name': 'Actividad presupuestaria',
                'verbose_name_plural': 'Actividades presupuestarias',
                'ordering': ['proyecto', 'codigo'],
                'unique_together': {('codigo', 'proyecto', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='LineaPresupuestaria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('entidad', models.CharField(max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_plurianual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe_gestion_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('version', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='presupuesto.actividadpresupuestaria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='organizacion.direccionadministrativa')),
                ('entidad_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.entidadtransferencia')),
                ('finalidad_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.finalidadfuncion')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.fuentefinanciamiento')),
                ('objeto_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.objetogasto')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_presupuestarias', to='indicadores.operacion')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='catalogos.organismofinanciador')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='organizacion.unidadejecutora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='presupuesto.programapresupuestario')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='presupuesto.proyectopresupuestario')),
            ],
            options={
                'verbose_name': 'Línea presupuestaria',
                'verbose_name_plural': 'Líneas presupuestarias',
                'ordering': ['gestion', 'programa__codigo'],
                'indexes': [models.Index(fields=['gestion', 'programa', 'fuente', 'objeto_gasto'], name='presupuesto_gestion_5aa8e8_idx'), models.Index(fields=['gestion', 'ue'], name='presupuesto_gestion_db6bb8_idx')],
            },
        ),
    ]
