# Generated by Django 6.0.7 on 2026-08-04 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0006_inmutabilidad_codigo_oficial'),
        ('catalogos', '0002_objetogasto_nivel_objetogasto_padre_and_more'),
        ('organizacion', '0001_initial'),
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProgramatica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_compuesto', models.CharField(editable=False, max_length=200)),
                ('codigo_fuente', models.CharField(max_length=200)),
                ('procedencia_normativa', models.CharField(max_length=500)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='presupuesto.actividadpresupuestaria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='organizacion.direccionadministrativa')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='catalogos.clasificadorinstitucional')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='presupuesto.programapresupuestario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='presupuesto.proyectopresupuestario')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='organizacion.unidadejecutora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_clasificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_programaticas', to='catalogos.versionclasificador')),
            ],
            options={
                'verbose_name': 'Categoría programática',
                'verbose_name_plural': 'Categorías programáticas',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPresupuestariaUnidad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('monto_formulado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_vigente', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias', to='articulacion.actividadpoau')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias_unidad', to='catalogos.fuentefinanciamiento')),
                ('objeto_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias_unidad', to='catalogos.objetogasto')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias', to='articulacion.operacionpoau')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias_unidad', to='catalogos.organismofinanciador')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias', to='articulacion.tareapoau')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_presupuestarias', to='organizacion.unidadorganizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria_programatica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='presupuesto.categoriaprogramatica')),
            ],
            options={
                'verbose_name': 'Asignación presupuestaria por unidad',
                'verbose_name_plural': 'Asignaciones presupuestarias por unidad',
            },
        ),
        migrations.AddIndex(
            model_name='categoriaprogramatica',
            index=models.Index(fields=['version_clasificador', 'entidad'], name='presupuesto_version_868fed_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaprogramatica',
            index=models.Index(fields=['da', 'ue'], name='presupuesto_da_id_dfc4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaprogramatica',
            index=models.Index(fields=['programa', 'proyecto', 'actividad'], name='presupuesto_program_eebba8_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriaprogramatica',
            constraint=models.UniqueConstraint(fields=('version_clasificador', 'entidad', 'da', 'ue', 'programa', 'proyecto', 'actividad'), name='uniq_categoria_programatica_apertura'),
        ),
        migrations.AddConstraint(
            model_name='categoriaprogramatica',
            constraint=models.UniqueConstraint(fields=('version_clasificador', 'codigo_compuesto'), name='uniq_categoria_programatica_codigo'),
        ),
        migrations.AddIndex(
            model_name='asignacionpresupuestariaunidad',
            index=models.Index(fields=['gestion', 'unidad'], name='presupuesto_gestion_9e7f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionpresupuestariaunidad',
            index=models.Index(fields=['objeto_gasto', 'gestion'], name='presupuesto_objeto__6a0408_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionpresupuestariaunidad',
            index=models.Index(fields=['categoria_programatica'], name='presupuesto_categor_3e54f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operacion__isnull', False), ('actividad__isnull', True), ('tarea__isnull', True)), models.Q(('operacion__isnull', True), ('actividad__isnull', False), ('tarea__isnull', True)), models.Q(('operacion__isnull', True), ('actividad__isnull', True), ('tarea__isnull', False)), _connector='OR'), name='asignacion_exactamente_un_nivel'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.CheckConstraint(condition=models.Q(('monto_formulado__gte', 0)), name='asignacion_formulado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.CheckConstraint(condition=models.Q(('monto_vigente__gte', 0)), name='asignacion_vigente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.CheckConstraint(condition=models.Q(('monto_ejecutado__gte', 0)), name='asignacion_ejecutado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.CheckConstraint(condition=models.Q(('monto_ejecutado__lte', models.F('monto_vigente'))), name='asignacion_ejecutado_hasta_vigente'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpresupuestariaunidad',
            constraint=models.UniqueConstraint(fields=('categoria_programatica', 'fuente', 'organismo', 'objeto_gasto', 'unidad', 'operacion', 'actividad', 'tarea', 'gestion'), name='uniq_asignacion_presupuestaria_unidad', nulls_distinct=False),
        ),
    ]
