# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('pad', '0004_migrar_programaciones'),
        ('planificacion', '0003_planversion'),
        ('poau', '0002_poauactividad_accion_corto_plazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Gestión')),
                ('evaluation_type', models.CharField(choices=[('anual', 'Anual'), ('medio_termino', 'Medio Término'), ('final', 'Final'), ('especifica', 'Específica')], max_length=20, verbose_name='Tipo de Evaluación')),
                ('period', models.CharField(choices=[('Q1', 'Primer Trimestre'), ('Q2', 'Segundo Trimestre'), ('Q3', 'Tercer Trimestre'), ('Q4', 'Cuarto Trimestre'), ('S1', 'Primer Semestre'), ('S2', 'Segundo Semestre'), ('AN', 'Anual')], default='AN', max_length=2, verbose_name='Período')),
                ('responsible_team', models.TextField(blank=True, help_text='Nombres del equipo encargado de la evaluación', verbose_name='Equipo Responsable')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('aprobada', 'Aprobada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('conclusions', models.TextField(blank=True, verbose_name='Conclusiones')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones Generales')),
                ('approved_document', models.FileField(blank=True, null=True, upload_to='evaluaciones/aprobados/%Y/', verbose_name='Documento Aprobado')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='planificacion.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fiscal_year', 'evaluation_type'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion', models.CharField(choices=[('eficacia', 'Eficacia'), ('eficiencia', 'Eficiencia'), ('efectividad', 'Efectividad'), ('pertinencia', 'Pertinencia'), ('impacto', 'Impacto'), ('sostenibilidad', 'Sostenibilidad')], max_length=20, verbose_name='Criterio')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Puntaje de 0 a 100', max_digits=5, verbose_name='Puntaje')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Peso relativo del criterio (0 a 1)', max_digits=5, verbose_name='Peso')),
                ('justification', models.TextField(blank=True, verbose_name='Justificación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='evaluacion.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
                'ordering': ['evaluacion', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='LeccionAprendida',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('tecnica', 'Técnica'), ('organizacional', 'Organizacional'), ('financiera', 'Financiera'), ('institucional', 'Institucional')], max_length=20, verbose_name='Categoría')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='evaluacion.evaluacion', verbose_name='Evaluación')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lección Aprendida',
                'verbose_name_plural': 'Lecciones Aprendidas',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('responsible_unit', models.CharField(blank=True, max_length=300, verbose_name='Unidad Responsable')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cumplida', 'Cumplida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='evaluacion.evaluacion', verbose_name='Evaluación')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_global', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje Global')),
                ('status', models.CharField(choices=[('cumple', 'Cumple'), ('parcial', 'Cumple Parcialmente'), ('no_cumple', 'No Cumple')], default='parcial', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluacion.evaluacion', verbose_name='Evaluación')),
                ('poau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_evaluacion', to='poau.poau', verbose_name='POAU')),
                ('resultado_pad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_evaluacion', to='pad.resultadoterritorial', verbose_name='Resultado PAD')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_evaluacion', to='organizacion.unidadorganizacional', verbose_name='Unidad Organizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación',
                'verbose_name_plural': 'Resultados de Evaluación',
                'ordering': ['-score_global'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['fiscal_year', 'evaluation_type'], name='evaluacion__fiscal__4e8b31_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['status'], name='evaluacion__status_0c36f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('plan', 'fiscal_year', 'evaluation_type', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='criterioevaluacion',
            unique_together={('evaluacion', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='resultadoevaluacion',
            index=models.Index(fields=['evaluacion', 'status'], name='evaluacion__evaluac_8c20b2_idx'),
        ),
    ]
