# Generated by Django 6.0.7 on 2026-08-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('planificacion', '0005_tipoinstrumento_tiponodoestrategico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='version_instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='planificacion.versioninstrumento', verbose_name='Versión de instrumento (V2)'),
        ),
    ]
