# Generated by Django 6.0.7 on 2026-08-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_evaluacion_version_instrumento'),
        ('planificacion', '0005_tipoinstrumento_tiponodoestrategico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='planificacion.plan', verbose_name='Plan'),
        ),
    ]
