# Generated by Django 6.0.7 on 2026-08-17 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_evaluacion_gestion_fk'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        ('planificacion', '0006_nodoestrategico_planificaci_version_0c0b75_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evaluacion',
            name='evaluacion__fiscal__4e8b31_idx',
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['gestion', 'evaluation_type'], name='evaluacion__gestion_c6e108_idx'),
        ),
    ]
