# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('poa_unidad', 'POA por unidad'), ('poa_institucional', 'POA institucional consolidado'), ('acciones_mediano', 'Acciones de mediano plazo'), ('acciones_corto', 'Acciones de corto plazo'), ('matriz_resultados', 'Matriz de resultados'), ('programacion_fisica', 'Programación física trimestral'), ('presupuesto_plurianual', 'Presupuesto plurianual'), ('presupuesto_anual', 'Presupuesto anual por programas'), ('llave_presupuestaria', 'Llave presupuestaria detallada'), ('techos_saldos', 'Techos y saldos'), ('proyectos_inversion', 'Proyectos de inversión'), ('asignaciones_obligatorias', 'Asignaciones obligatorias'), ('observaciones', 'Observaciones'), ('expediente_aprobacion', 'Expediente de aprobación'), ('auditoria', 'Reporte de auditoría'), ('mapa_inversion', 'Mapa de inversión territorial')], max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV'), ('geojson', 'GeoJSON')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('hash_archivo', models.CharField(blank=True, editable=False, max_length=64)),
                ('parametros', models.JSONField(blank=True, help_text='Parámetros usados para generar el reporte', null=True)),
                ('gestion', models.PositiveIntegerField()),
                ('version_datos', models.CharField(blank=True, help_text='Versión de los datos al generar', max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
