# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='UnidadTerritorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('otb', 'OTB'), ('comunidad', 'Comunidad'), ('zona', 'Zona'), ('establecimiento', 'Establecimiento'), ('otro', 'Otro')], max_length=50)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroide', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('poblacion', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_territoriales', to='territorio.distrito')),
            ],
            options={
                'verbose_name': 'Unidad territorial',
                'verbose_name_plural': 'Unidades territoriales',
                'ordering': ['distrito', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacionTerritorial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidad', models.CharField(help_text='Nombre del modelo asociado', max_length=50)),
                ('entidad_id', models.CharField(help_text='ID del registro', max_length=100)),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Geometría en EPSG:32719 (métrica)', null=True, srid=32719)),
                ('geometria_4326', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Geometría en EPSG:4326 (web)', null=True, srid=4326)),
                ('direccion_referencia', models.CharField(blank=True, max_length=500)),
                ('gestion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizaciones', to='territorio.distrito')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidad_territorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizaciones', to='territorio.unidadterritorial')),
            ],
            options={
                'verbose_name': 'Localización territorial',
                'verbose_name_plural': 'Localizaciones territoriales',
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='territorio__entidad_f7abd9_idx'), models.Index(fields=['gestion'], name='territorio__gestion_5530ce_idx')],
            },
        ),
    ]
