# Generated by Django 6.0.7 on 2026-08-28 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.territorio.models import clave_organizacion


def rellenar_nombre_busqueda(apps, schema_editor):
    """Calcula la clave de las filas que ya existian, antes del indice unico.

    `nombre_busqueda` nace en blanco, y el `AddConstraint` que viene despues
    exige (distrito, nombre_busqueda) unico. Sobre una base que ya tenga dos o
    mas organizaciones en el mismo distrito —produccion tiene 361 repartidas en
    doce, con 73 en el mas cargado— la migracion abortaria con IntegrityError.
    En desarrollo no se noto porque la tabla estaba vacia al aplicarla y el
    padron se importo despues, calculando la clave en `save()`.

    Se usa `clave_organizacion` del modelo real a proposito: si el algoritmo
    cambia, esta migracion historica dejaria de coincidir con lo que escribe
    `save()`, y ese desacuerdo es peor que el acoplamiento.
    """
    UnidadTerritorial = apps.get_model('territorio', 'UnidadTerritorial')
    for unidad in UnidadTerritorial.objects.all().only('id', 'nombre'):
        UnidadTerritorial.objects.filter(pk=unidad.pk).update(
            nombre_busqueda=clave_organizacion(unidad.nombre),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_alter_localizacionterritorial_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirigenteTerritorial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField(db_index=True, help_text='Año del padrón del que salió el dato.', verbose_name='Gestión')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del dirigente')),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Dirigente territorial',
                'verbose_name_plural': 'Dirigentes territoriales',
                'ordering': ['unidad', '-gestion', 'cargo'],
            },
        ),
        migrations.AddField(
            model_name='unidadterritorial',
            name='activa',
            field=models.BooleanField(default=True, help_text='Se desmarca en vez de borrar: las actas ya emitidas la citan.', verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='unidadterritorial',
            name='nombre_busqueda',
            field=models.TextField(blank=True, db_index=True, verbose_name='Nombre normalizado'),
        ),
        migrations.AddField(
            model_name='unidadterritorial',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='unidadterritorial',
            name='tipo',
            field=models.CharField(choices=[('otb', 'OTB'), ('junta_vecinal', 'Junta vecinal'), ('comunidad', 'Comunidad'), ('sindicato', 'Sindicato agrario'), ('subcentral', 'Subcentral'), ('zona', 'Zona'), ('establecimiento', 'Establecimiento'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.RunPython(
            rellenar_nombre_busqueda, migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='unidadterritorial',
            constraint=models.UniqueConstraint(fields=('distrito', 'nombre_busqueda'), name='unidad_territorial_unica_por_distrito'),
        ),
        migrations.AddField(
            model_name='dirigenteterritorial',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dirigenteterritorial',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirigentes', to='territorio.unidadterritorial', verbose_name='Organización territorial'),
        ),
        migrations.AddField(
            model_name='dirigenteterritorial',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dirigenteterritorial',
            constraint=models.UniqueConstraint(fields=('unidad', 'gestion', 'cargo'), name='dirigente_unico_por_gestion_y_cargo'),
        ),
    ]
