# Generated by Django 6.0.7 on 2026-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_organizaciones_territoriales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirigenteterritorial',
            name='gestion',
            field=models.PositiveIntegerField(db_index=True, help_text='Gestión POA a la que sirve este padrón, no el año en que se levantó: es la que busca el formulario del acta.', verbose_name='Gestión'),
        ),
    ]
