# Generated by Django 6.0.7 on 2026-07-20 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cause', models.TextField(verbose_name='Causa')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('due_date', models.DateField(verbose_name='Fecha Límite')),
                ('expected_result', models.TextField(verbose_name='Resultado Esperado')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En Ejecución'), ('cumplida', 'Cumplida'), ('incumplida', 'Incumplida'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('evidence', models.TextField(blank=True, null=True, verbose_name='Evidencia')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
            ],
            options={
                'verbose_name': 'Acción Correctiva',
                'verbose_name_plural': 'Acciones Correctivas',
                'ordering': ['-gestion', 'status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CompromisoAccionCorrectiva',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('due_date', models.DateField(verbose_name='Fecha Límite')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('cumplido', 'Cumplido'), ('incumplido', 'Incumplido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cumplimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Compromiso de Acción Correctiva',
                'verbose_name_plural': 'Compromisos de Acciones Correctivas',
                'ordering': ['due_date', 'status'],
            },
        ),
    ]
