# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acciones_correctivas', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncorrectiva',
            name='alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_correctivas', to='seguimiento.alerta', verbose_name='Alerta'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_correctivas', to='seguimiento.entradaseguimiento', verbose_name='Entrada de Seguimiento'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_correctivas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='responsible_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_correctivas', to='organizacion.unidadorganizacional', verbose_name='Unidad Responsable'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_verificadas', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='compromisoaccioncorrectiva',
            name='accion_correctiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='acciones_correctivas.accioncorrectiva', verbose_name='Acción Correctiva'),
        ),
        migrations.AddField(
            model_name='compromisoaccioncorrectiva',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromisoaccioncorrectiva',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accioncorrectiva',
            index=models.Index(fields=['gestion', 'status'], name='acciones_co_gestion_1132fc_idx'),
        ),
        migrations.AddIndex(
            model_name='accioncorrectiva',
            index=models.Index(fields=['due_date'], name='acciones_co_due_dat_4b357d_idx'),
        ),
        migrations.AddIndex(
            model_name='accioncorrectiva',
            index=models.Index(fields=['responsible'], name='acciones_co_respons_35878b_idx'),
        ),
        migrations.AddIndex(
            model_name='compromisoaccioncorrectiva',
            index=models.Index(fields=['status'], name='acciones_co_status_4389bc_idx'),
        ),
        migrations.AddIndex(
            model_name='compromisoaccioncorrectiva',
            index=models.Index(fields=['due_date'], name='acciones_co_due_dat_720d9e_idx'),
        ),
    ]
