# Generated by Django 6.0.7 on 2026-07-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativa',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
    ]
