# Generated by Django 6.0.7 on 2026-07-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0002_normativa_observacion'),
        ('planificacion', '0004_alter_nodoplanificacion_nivel_alter_plan_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadopad',
            name='nodo_pdesa',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel': 'accion', 'plan__tipo': 'pdesa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_pad', to='planificacion.nodoplanificacion', verbose_name='Nodo PDESA'),
        ),
    ]
