# Generated by Django 6.0.7 on 2026-07-30 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0003_resultadopad_nodo_pdesa'),
        ('organizacion', '0001_initial'),
        ('planificacion', '0004_alter_nodoplanificacion_nivel_alter_plan_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpoa',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='accionpoa',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='accionpoa',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='accionpoa',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='accionpoa',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='accionpoa',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='codigo_completo_articulacion',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, verbose_name='Código completo de articulación'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='codigo_fuente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código fuente original'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='codigo_normalizado',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Código normalizado'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correlativo del nivel'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='estado_codigo',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado del código'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='segmento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Segmento del nivel'),
        ),
        migrations.AddConstraint(
            model_name='accionpoa',
            constraint=models.UniqueConstraint(fields=('producto_pei', 'gestion', 'correlativo'), name='uniq_accion_poa_padre_gestion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='actividadpoau',
            constraint=models.UniqueConstraint(fields=('operacion', 'correlativo'), name='uniq_actividad_poau_padre_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='operacionpoau',
            constraint=models.UniqueConstraint(fields=('accion_poa', 'correlativo'), name='uniq_operacion_poau_padre_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='productopad',
            constraint=models.UniqueConstraint(fields=('resultado_pad', 'correlativo'), name='uniq_producto_pad_padre_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='productopei',
            constraint=models.UniqueConstraint(fields=('resultado_pei', 'correlativo'), name='uniq_producto_pei_padre_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='resultadopad',
            constraint=models.UniqueConstraint(fields=('vigencia_desde', 'correlativo'), name='uniq_resultado_pad_gestion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='resultadopei',
            constraint=models.UniqueConstraint(fields=('vigencia_desde', 'correlativo'), name='uniq_resultado_pei_gestion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='tareapoau',
            constraint=models.UniqueConstraint(fields=('actividad', 'correlativo'), name='uniq_tarea_poau_padre_correlativo'),
        ),
    ]
