# Generated by Django 6.0.7 on 2026-08-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0004_mixin_codigo_segmentado'),
        ('codificacion', '0008_homologacion_append_only_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpoa',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='actividadpoau',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='entidad_territorial_cgeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_pad', to='codificacion.entidadterritorialcgeo', verbose_name='Entidad territorial CGEO'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='lineamiento_pad_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_pad', to='codificacion.lineamientopad', verbose_name='Lineamiento PAD de catálogo'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='resultado_sectorial_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_pad', to='codificacion.resultadosectorial', verbose_name='Resultado sectorial de catálogo'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='entidad_codificadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_pei', to='codificacion.entidadcodificadora', verbose_name='Entidad codificadora'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='articulacion_incompleta',
            field=models.BooleanField(default=True, editable=False, verbose_name='Articulación incompleta'),
        ),
    ]
