# Generated by Django 6.0.7 on 2026-08-13 11:57
# Renumerado de 0009 (rama feature/s2-nucleo-techo) a 0007: main solo llega
# hasta 0006_inmutabilidad_codigo_oficial.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0006_inmutabilidad_codigo_oficial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorMatrizPAD',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.IntegerField(default=2026, verbose_name='Gestión')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETO', 'Completo')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('datos', models.JSONField(default=dict, help_text='Secciones de cabecera p1_nacional..p5_lineamiento + colección resultados[] (cada resultado con sus productos).', verbose_name='Datos del wizard')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_resultado_pad', models.ForeignKey(blank=True, help_text='Se llena al materializar el borrador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_matriz_pad', to='articulacion.resultadopad', verbose_name='Resultado PAD materializado')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrador de Matriz PAD',
                'verbose_name_plural': 'Borradores de Matrices PAD',
                'ordering': ['-created_at'],
            },
        ),
    ]
