# Generated by Django 6.0.7 on 2026-08-12 20:21

import uuid
from django.db import migrations, models

TABLA_TEMPORAL = 'articulacion_seed_meta_acuerdos'

CREAR_TABLA_TEMPORAL = f"""
CREATE TABLE {TABLA_TEMPORAL} (
    resultadopad_id uuid NOT NULL,
    tipo varchar(10) NOT NULL,
    codigo varchar(50) NOT NULL,
    PRIMARY KEY (resultadopad_id, tipo, codigo)
)
"""

ELIMINAR_TABLA_TEMPORAL = f'DROP TABLE IF EXISTS {TABLA_TEMPORAL}'


def capturar_metas_demo(apps, schema_editor):
    """Crea MetaAcuerdoInternacional desde los NDC/NDT demo de
    AcuerdoInternacional y respalda los vínculos M2M antes de que
    AlterField reconstruya las tablas intermedias (patrón 0003)."""
    Acuerdo = apps.get_model('articulacion', 'AcuerdoInternacional')
    Meta = apps.get_model('articulacion', 'MetaAcuerdoInternacional')
    Resultado = apps.get_model('articulacion', 'ResultadoPAD')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(CREAR_TABLA_TEMPORAL)

    for tipo in ('NDC', 'NDT'):
        campo = f'acuerdo_{tipo.lower()}'
        for acuerdo in Acuerdo.objects.filter(tipo_acuerdo=tipo):
            Meta.objects.get_or_create(
                tipo_acuerdo=tipo,
                codigo=acuerdo.codigo,
                defaults={
                    'denominacion': acuerdo.denominacion,
                    'instrumento_origen': 'migracion-acuerdo-internacional-demo',
                    'activo': acuerdo.activo,
                },
            )
        # Respaldo de vínculos previos (tablas intermedias aún presentes).
        for resultado in Resultado.objects.filter(
            **{f'{campo}__isnull': False},
        ).distinct():
            for acuerdo in getattr(resultado, campo).all():
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(
                        f'INSERT INTO {TABLA_TEMPORAL} '
                        '(resultadopad_id, tipo, codigo) VALUES (%s, %s, %s) '
                        'ON CONFLICT DO NOTHING',
                        [str(resultado.pk), tipo, acuerdo.codigo],
                    )


def restaurar_metas_demo(apps, schema_editor):
    """Re-vincula los resultados PAD a las metas NDC/NDT migradas."""
    Meta = apps.get_model('articulacion', 'MetaAcuerdoInternacional')
    Resultado = apps.get_model('articulacion', 'ResultadoPAD')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'SELECT resultadopad_id, tipo, codigo FROM {TABLA_TEMPORAL}'
        )
        filas = cursor.fetchall()
        cursor.execute(ELIMINAR_TABLA_TEMPORAL)

    for resultadopad_id, tipo, codigo in filas:
        meta = Meta.objects.filter(tipo_acuerdo=tipo, codigo=codigo).first()
        resultado = Resultado.objects.filter(pk=resultadopad_id).first()
        if meta is not None and resultado is not None:
            getattr(resultado, f'acuerdo_{tipo.lower()}').add(meta)


def retirar_metas_demo(apps, schema_editor):
    """Reverse de capturar: elimina las metas demo creadas."""
    Meta = apps.get_model('articulacion', 'MetaAcuerdoInternacional')
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(ELIMINAR_TABLA_TEMPORAL)
    Meta.objects.filter(
        instrumento_origen='migracion-acuerdo-internacional-demo',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0006_inmutabilidad_codigo_oficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAcuerdoInternacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_acuerdo', models.CharField(choices=[('NDC', 'NDC'), ('NDT', 'NDT'), ('KMGBF', 'KMGBF')], max_length=10, verbose_name='Tipo de acuerdo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('denominacion', models.TextField(verbose_name='Denominación')),
                ('instrumento_origen', models.CharField(blank=True, default='', max_length=50, verbose_name='Instrumento de origen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('metadatos_importacion', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meta de acuerdo internacional',
                'verbose_name_plural': 'Metas de acuerdos internacionales',
                'ordering': ['tipo_acuerdo', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('tipo_acuerdo', 'codigo'), name='uniq_meta_acuerdo_tipo_codigo')],
            },
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='acuerdo_kmgbf',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_acuerdo': 'KMGBF'}, related_name='resultados_pad_kmgbf', to='articulacion.metaacuerdointernacional', verbose_name='Acuerdo KMGBF'),
        ),
        migrations.RunPython(capturar_metas_demo, retirar_metas_demo),
        migrations.AlterField(
            model_name='resultadopad',
            name='acuerdo_ndc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_acuerdo': 'NDC'}, related_name='resultados_pad_ndc', to='articulacion.metaacuerdointernacional', verbose_name='Acuerdo NDC'),
        ),
        migrations.AlterField(
            model_name='resultadopad',
            name='acuerdo_ndt',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_acuerdo': 'NDT'}, related_name='resultados_pad_ndt', to='articulacion.metaacuerdointernacional', verbose_name='Acuerdo NDT'),
        ),
        migrations.RunPython(restaurar_metas_demo, migrations.RunPython.noop),
    ]
