# Generated by Django 6.0.6 on 2026-08-17 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0007_borradormatrizpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorcadena',
            name='resultado_pei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='articulacion.resultadopei', verbose_name='Resultado PEI'),
        ),
        migrations.AddField(
            model_name='productopei',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('INTERMEDIO', 'Intermedio'), ('FINAL', 'Final'), ('TERMINAL', 'Terminal')], max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_componente_pdesa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código componente PDESA'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_eje_pgdesa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código eje PGDESA'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_meta_3030',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código meta 30x30'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_ndc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código NDC'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_ndt',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código NDT'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_ods',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código ODS'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_resultado_sectorial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código resultado sectorial PES'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_resultado_territorial',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código resultado territorial'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='cod_sector',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código sector'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='objetivo_efecto',
            field=models.TextField(blank=True, verbose_name='Objetivo de efecto'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='objetivo_estrategico',
            field=models.TextField(blank=True, verbose_name='Objetivo estratégico institucional'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='objetivo_impacto',
            field=models.TextField(blank=True, verbose_name='Objetivo de impacto'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='resultado_pad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_pei', to='articulacion.resultadopad', verbose_name='Resultado PAD'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='resultado_sectorial',
            field=models.TextField(blank=True, verbose_name='Resultado sectorial'),
        ),
        migrations.AddField(
            model_name='resultadopei',
            name='sector',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sector'),
        ),
    ]
