# Generated by Django 6.0.7 on 2026-08-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0007_metaacuerdointernacional_resultadopad_acuerdo_kmgbf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorcadena',
            name='presupuesto_anual',
            field=models.JSONField(blank=True, help_text='Programación financiera anual del quinquenio (Matriz B, sin decimales en captura).', null=True, verbose_name='Presupuesto anual 2026-2030 (Bs.)'),
        ),
        migrations.AddField(
            model_name='indicadorcadena',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto referencial del PAD para el quinquenio (Matriz B, sin decimales en captura).', max_digits=20, null=True, verbose_name='Presupuesto total PAD (Bs.)'),
        ),
        migrations.AddField(
            model_name='indicadorcadena',
            name='resultado_pad',
            field=models.ForeignKey(blank=True, help_text='Indicador a nivel de resultado PAD (Matriz A, fila de resultado).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='articulacion.resultadopad', verbose_name='Resultado PAD'),
        ),
        migrations.AddField(
            model_name='productopad',
            name='cuenta_con_financiamiento',
            field=models.BooleanField(default=False, help_text='Columna U de la Matriz A (SÍ/NO) a nivel de fila de producto.', verbose_name='Cuenta con financiamiento'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='cuenta_con_financiamiento',
            field=models.BooleanField(default=False, help_text='Columna U de la Matriz A (SÍ/NO) a nivel de fila.', verbose_name='Cuenta con financiamiento'),
        ),
        migrations.AddField(
            model_name='resultadopad',
            name='politica',
            field=models.TextField(blank=True, help_text='Directriz territorial (columna C de la Matriz A).', verbose_name='Política'),
        ),
    ]
