# Generated by Django 6.0.7 on 2026-08-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0008_matriz_pei_articulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionobjetogasto',
            name='cargo_reacp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo del REACP'),
        ),
        migrations.AddField(
            model_name='asignacionobjetogasto',
            name='fecha_requerimiento',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fecha en la que se requiere el pago (mes estimado)'),
        ),
        migrations.AddField(
            model_name='asignacionobjetogasto',
            name='medio_verificacion',
            field=models.TextField(blank=True, verbose_name='Medio de verificación'),
        ),
        migrations.AddField(
            model_name='asignacionobjetogasto',
            name='programacion_mensual',
            field=models.JSONField(blank=True, null=True, verbose_name='Programación presupuestaria mensual'),
        ),
    ]
