# Generated by Django 6.0.7 on 2026-08-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0009_poau_programacion_presupuestaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borradormatrizpad',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pad_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='estado_revision',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VALIDADO', 'Validado por el técnico'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20, verbose_name='Estado de revisión'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='observado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Observado en'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='observado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pad_observadas', to=settings.AUTH_USER_MODEL, verbose_name='Observado por'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validado en'),
        ),
        migrations.AddField(
            model_name='borradormatrizpad',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pad_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
