# Generated by Django 6.0.7 on 2026-08-18 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0010_revision_matriz_pad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorMatrizPEI',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.IntegerField(default=2026, verbose_name='Gestión inicial')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETO', 'Completo')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('datos', models.JSONField(default=dict, verbose_name='Datos del asistente')),
                ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VALIDADO', 'Validado por el técnico'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20, verbose_name='Estado de revisión')),
                ('validado_en', models.DateTimeField(blank=True, null=True, verbose_name='Validado en')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('observado_en', models.DateTimeField(blank=True, null=True, verbose_name='Observado en')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pei_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_resultado_pei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_matriz_pei', to='articulacion.resultadopei', verbose_name='Resultado PEI materializado')),
                ('observado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pei_observadas', to=settings.AUTH_USER_MODEL, verbose_name='Observado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices_pei_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Borrador de Matriz PEI',
                'verbose_name_plural': 'Borradores de Matrices PEI',
                'ordering': ['-created_at'],
            },
        ),
    ]
