# Generated by Django 6.0.7 on 2026-08-19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0012_borrador_matriz_poa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilidadAcuerdoInternacional',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'tipo_relacion',
                    models.CharField(
                        choices=[
                            ('OFICIAL_EXPLICITA', 'Oficial explícita'),
                            ('DERIVADA_DOCUMENTAL', 'Derivada documental'),
                            ('SUGERENCIA_SEMANTICA', 'Sugerencia IA'),
                        ],
                        max_length=30,
                        verbose_name='Tipo de relación',
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('VALIDADA', 'Validada'),
                            ('CANDIDATA', 'Candidata'),
                            ('RECHAZADA', 'Rechazada'),
                        ],
                        default='CANDIDATA',
                        max_length=20,
                        verbose_name='Estado',
                    ),
                ),
                (
                    'confianza',
                    models.CharField(
                        choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')],
                        default='BAJA',
                        max_length=10,
                        verbose_name='Confianza',
                    ),
                ),
                (
                    'fuente_url',
                    models.URLField(
                        blank=True,
                        default='',
                        max_length=500,
                        verbose_name='URL fuente',
                    ),
                ),
                (
                    'fuente_titulo',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=300,
                        verbose_name='Título fuente',
                    ),
                ),
                (
                    'fuente_version',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=150,
                        verbose_name='Versión fuente',
                    ),
                ),
                (
                    'localizador',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=200,
                        verbose_name='Localizador',
                    ),
                ),
                ('evidencia', models.TextField(blank=True, default='', verbose_name='Evidencia')),
                (
                    'justificacion',
                    models.TextField(blank=True, default='', verbose_name='Justificación'),
                ),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                (
                    'revisado_en',
                    models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'destino',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='compatibilidades_destino',
                        to='articulacion.acuerdointernacional',
                        verbose_name='Acuerdo destino',
                    ),
                ),
                (
                    'origen',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='compatibilidades_origen',
                        to='articulacion.acuerdointernacional',
                        verbose_name='Acuerdo origen',
                    ),
                ),
                (
                    'revisado_por',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='compatibilidades_acuerdos_revisadas',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuario revisor',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Compatibilidad de acuerdo internacional',
                'verbose_name_plural': 'Compatibilidades de acuerdos internacionales',
                'ordering': ['origen__codigo', 'destino__codigo', 'tipo_relacion', 'fuente_url'],
                'indexes': [
                    models.Index(fields=['origen', 'destino', 'activo'], name='articulacio_origen_1c85f8_idx'),
                    models.Index(fields=['destino', 'estado', 'tipo_relacion'], name='articulacio_destino_1d4388_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('origen', 'destino', 'tipo_relacion', 'fuente_url'),
                        name='uniq_compat_acuerdo_origen_destino_tipo_fuente',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('origen', models.F('destino')), _negated=True),
                        name='compat_acuerdo_origen_destino_distintos',
                    ),
                ],
            },
        ),
    ]
