# Generated by Django 6.0.7 on 2026-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0013_compatibilidad_acuerdo_internacional'),
    ]

    def migrar_estados(apps, schema_editor):
        """`REFERENCIAL` era el default de un campo sin choices: pasa a BORRADOR.

        Se usan los modelos históricos a propósito: si esta migración importara
        los modelos vivos, cambiar el modelo mañana rompería la migración de
        ayer.
        """
        for modelo in ('OperacionPOAU', 'ActividadPOAU', 'TareaPOAU'):
            apps.get_model('articulacion', modelo).objects.exclude(
                estado__in=['BORRADOR', 'VALIDADO', 'OBSERVADO', 'APROBADO']
            ).update(estado='BORRADOR')

    def revertir_estados(apps, schema_editor):
        for modelo in ('OperacionPOAU', 'ActividadPOAU', 'TareaPOAU'):
            apps.get_model('articulacion', modelo).objects.filter(
                estado='BORRADOR'
            ).update(estado='REFERENCIAL')

    operations = [
        migrations.AddField(
            model_name='actividadpoau',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='operacionpoau',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='tareapoau',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='actividadpoau',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='operacionpoau',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tareapoau',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.RunPython(migrar_estados, revertir_estados),
    ]
