# Generated by Django 6.0.7 on 2026-08-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0017_categoria_sin_numero_queda_vacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionobjetogasto',
            name='codigo_asignacion',
            field=models.CharField(max_length=60, verbose_name='Código asignación'),
        ),
    ]
