# Generated by Django 6.0.7 on 2026-09-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0018_alter_asignacionobjetogasto_codigo_asignacion'),
        ('gestion', '0005_candado_gestion_habilitada'),
        ('organizacion', '0003_area_y_clase_de_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionProgramacionFisica',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('excel', 'Excel'), ('google_sheets', 'Google Sheets')], max_length=20)),
                ('fuente_nombre', models.CharField(blank=True, default='', max_length=300)),
                ('hoja', models.CharField(blank=True, default='', max_length=200)),
                ('fuente_sha256', models.CharField(max_length=64)),
                ('filas_normalizadas', models.JSONField(default=list)),
                ('errores', models.JSONField(default=list)),
                ('resumen', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('VALIDO', 'Válido'), ('INVALIDO', 'Inválido'), ('APLICADO', 'Aplicado')], max_length=12)),
                ('expira_en', models.DateTimeField()),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_programacion_fisica', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones_programacion_fisica', to='gestion.gestionfiscal')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_programacion_fisica', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Importación de programación física POAU',
                'verbose_name_plural': 'Importaciones de programación física POAU',
                'db_table': 'articulacion_importacion_programacion_fisica',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creado_por', 'estado', 'expira_en'], name='articulacio_creado__7747c1_idx'), models.Index(fields=['gestion', 'unidad'], name='articulacio_gestion_44e32e_idx')],
            },
        ),
    ]
