# Generated by Django 6.0.7 on 2026-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0022_asignacion_gasto_actividad_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionpoau',
            name='categoria_programatica',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoría programática'),
        ),
    ]
