# Generated by Django 6.0.7 on 2026-09-05 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0023_operacion_categoria_programatica'),
        ('catalogos', '0012_catalogos_alineados_a_gestion_2027'),
        ('organizacion', '0003_area_y_clase_de_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoUnidadCategoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_programatica', models.CharField(max_length=50, verbose_name='Categoría programática')),
                ('denominacion', models.CharField(blank=True, max_length=500, verbose_name='Denominación')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo disponible')),
                ('filas_origen', models.PositiveIntegerField(default=0, verbose_name='Filas de la planilla de origen')),
                ('observacion', models.TextField(blank=True, help_text='Por qué esta fila se aparta de la planilla, si es el caso.', verbose_name='Observación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_unidad_categoria_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldos_unidad_categoria', to='catalogos.fuentefinanciamiento', verbose_name='Fuente de financiamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldos_unidad_categoria', to='catalogos.organismofinanciador', verbose_name='Organismo financiador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_categoria', to='organizacion.unidadorganizacional', verbose_name='Unidad organizacional')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_unidad_categoria_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Saldo por unidad y categoría',
                'verbose_name_plural': 'Saldos por unidad y categoría',
                'ordering': ['unidad__codigo', 'categoria_programatica'],
                'indexes': [models.Index(fields=['unidad', 'categoria_programatica'], name='art_saldo_uni_cat_idx')],
                'constraints': [models.UniqueConstraint(fields=('unidad', 'categoria_programatica', 'fuente', 'organismo'), name='uniq_saldo_unidad_categoria_fuente_organismo', nulls_distinct=False)],
            },
        ),
    ]
