# Generated by Django 6.0.7 on 2026-09-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulacion', '0023_operacion_categoria_programatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionpoa',
            name='cargo_responsable',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Cargo responsable'),
        ),
        migrations.AlterField(
            model_name='operacionpoau',
            name='responsable',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='tareapoau',
            name='responsable',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Responsable'),
        ),
    ]
