# Generated by Django 6.0.7 on 2026-08-09 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMigrationMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_legacy', models.CharField(max_length=100)),
                ('modelo_legacy', models.CharField(max_length=100)),
                ('uuid_legacy', models.UUIDField()),
                ('tipo_destino', models.CharField(blank=True, default='', max_length=100)),
                ('uuid_destino', models.UUIDField(blank=True, null=True)),
                ('lote', models.CharField(default='inicial', max_length=100)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('migrado', 'Migrado'), ('reconciliado', 'Reconciliado'), ('discrepancia', 'Discrepancia'), ('retirado', 'Retirado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapa de migración legacy',
                'verbose_name_plural': 'Mapas de migración legacy',
                'ordering': ['app_legacy', 'modelo_legacy', 'uuid_legacy'],
                'constraints': [models.UniqueConstraint(fields=('app_legacy', 'modelo_legacy', 'uuid_legacy'), name='uniq_legacy_registro')],
            },
        ),
    ]
