# Generated by Django 6.0.7 on 2026-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legacymigrationmap'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demodatasetmanifest',
            table='nucleo_manifesto_dataset_demo',
        ),
        migrations.AlterModelTable(
            name='legacymigrationmap',
            table='nucleo_mapa_migraciones_legacy',
        ),
    ]
