# Generated by Django 6.0.7 on 2026-08-04 19:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objetogasto',
            name='nivel',
            field=models.CharField(blank=True, choices=[('grupo', 'Grupo'), ('subgrupo', 'Subgrupo'), ('partida', 'Partida'), ('detalle', 'Detalle')], max_length=20),
        ),
        migrations.AddField(
            model_name='objetogasto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='catalogos.objetogasto'),
        ),
        migrations.CreateModel(
            name='VersionClasificador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('institucional', 'Institucional'), ('objeto_gasto', 'Objeto del gasto'), ('fuente_financiamiento', 'Fuente de financiamiento'), ('organismo_financiador', 'Organismo financiador'), ('categoria_programatica', 'Categoría programática'), ('geografico_presupuestario', 'Geográfico presupuestario')], max_length=40)),
                ('gestion', models.PositiveIntegerField()),
                ('norma', models.CharField(blank=True, max_length=300)),
                ('fecha_norma', models.DateField(blank=True, null=True)),
                ('codigo_fuente', models.CharField(blank=True, max_length=100)),
                ('procedencia_normativa', models.CharField(blank=True, max_length=500)),
                ('hash_fuente', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'El hash debe ser un SHA-256 hexadecimal.')])),
                ('clasificacion_fuente', models.CharField(choices=[('oficial', 'Oficial'), ('referencial', 'Referencial'), ('tecnica', 'Técnica'), ('incierta', 'Incierta')], default='incierta', max_length=20)),
                ('vigente', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', '-gestion', '-fecha_norma'],
            },
        ),
        migrations.CreateModel(
            name='ClasificadorGeograficoPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=10)),
                ('codigo_fuente', models.CharField(max_length=50)),
                ('denominacion', models.CharField(max_length=300)),
                ('procedencia_normativa', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_clasificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_geograficas_presupuestarias', to='catalogos.versionclasificador')),
            ],
            options={
                'verbose_name': 'Clasificador geográfico presupuestario',
                'verbose_name_plural': 'Clasificadores geográficos presupuestarios',
            },
        ),
        migrations.AddField(
            model_name='fuentefinanciamiento',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuentes_financiamiento', to='catalogos.versionclasificador'),
        ),
        migrations.AddField(
            model_name='objetogasto',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_gasto', to='catalogos.versionclasificador'),
        ),
        migrations.AddField(
            model_name='organismofinanciador',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organismos_financiadores', to='catalogos.versionclasificador'),
        ),
        migrations.AddConstraint(
            model_name='fuentefinanciamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_fuente_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='objetogasto',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_objeto_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='organismofinanciador',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_organismo_codigo_version'),
        ),
        migrations.AddIndex(
            model_name='versionclasificador',
            index=models.Index(fields=['tipo', 'gestion', 'vigente'], name='catalogos_v_tipo_28716e_idx'),
        ),
        migrations.AddConstraint(
            model_name='versionclasificador',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('tipo', 'gestion'), name='uniq_clasificador_vigente_tipo_gestion'),
        ),
        migrations.AddConstraint(
            model_name='versionclasificador',
            constraint=models.CheckConstraint(condition=models.Q(('vigente', False), models.Q(('clasificacion_fuente', 'oficial'), models.Q(('norma', ''), _negated=True), ('fecha_norma__isnull', False), models.Q(('codigo_fuente', ''), _negated=True), models.Q(('procedencia_normativa', ''), _negated=True), models.Q(('hash_fuente', ''), _negated=True)), _connector='OR'), name='clasificador_vigente_fuente_oficial'),
        ),
        migrations.AddIndex(
            model_name='clasificadorgeograficopresupuestario',
            index=models.Index(fields=['version_clasificador', 'codigo_fuente'], name='catalogos_c_version_e77357_idx'),
        ),
        migrations.AddConstraint(
            model_name='clasificadorgeograficopresupuestario',
            constraint=models.UniqueConstraint(fields=('version_clasificador', 'departamento', 'provincia', 'municipio'), name='uniq_geo_presupuestario_version_codigo'),
        ),
    ]
