# Generated by Django 6.0.7 on 2026-08-12 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_blindaje_fuente_oficial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorEconomicoPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('denominacion', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField()),
                ('fuente_normativa', models.CharField(blank=True, max_length=500)),
                ('metadatos_importacion', models.JSONField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, help_text='Profundidad derivada del código (1, 2 o 3).', max_length=20, verbose_name='Nivel')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='catalogos.sectoreconomicopresupuestario', verbose_name='Padre')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sector económico presupuestario',
                'verbose_name_plural': 'Sectores económicos presupuestarios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionPlataforma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('modulo', models.CharField(max_length=30, verbose_name='Módulo')),
                ('control', models.CharField(max_length=100, verbose_name='Control')),
                ('regla', models.TextField(blank=True, verbose_name='Regla')),
                ('nivel', models.CharField(blank=True, default='ERROR', max_length=20, verbose_name='Nivel')),
                ('efecto', models.CharField(blank=True, default='BLOQUEA_ENVIO', max_length=30, verbose_name='Efecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('metadatos_importacion', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación de plataforma',
                'verbose_name_plural': 'Validaciones de plataforma',
                'ordering': ['modulo', 'codigo'],
            },
        ),
    ]
