# Generated by Django 6.0.7 on 2026-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_blindaje_fuente_oficial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clasificadorgeograficopresupuestario',
            new_name='catalogo_ub_version_948f51_idx',
            old_name='catalogos_c_version_e77357_idx',
        ),
        migrations.RenameIndex(
            model_name='versionclasificador',
            new_name='catalogo_ve_tipo_cb6930_idx',
            old_name='catalogos_v_tipo_28716e_idx',
        ),
        migrations.AlterModelTable(
            name='clasificadorgeograficopresupuestario',
            table='catalogo_ubicacion_geografica_presupuestaria',
        ),
        migrations.AlterModelTable(
            name='clasificadorinstitucional',
            table='catalogo_clasificador_institucional',
        ),
        migrations.AlterModelTable(
            name='entidadtransferencia',
            table='catalogo_entidad_transferencia',
        ),
        migrations.AlterModelTable(
            name='finalidadfuncion',
            table='catalogo_finalidad_funcion',
        ),
        migrations.AlterModelTable(
            name='fuentefinanciamiento',
            table='catalogo_fuente_financiamiento',
        ),
        migrations.AlterModelTable(
            name='objetogasto',
            table='catalogo_objeto_gasto',
        ),
        migrations.AlterModelTable(
            name='organismofinanciador',
            table='catalogo_organismo_financiador',
        ),
        migrations.AlterModelTable(
            name='rubrorecurso',
            table='catalogo_rubro_recurso',
        ),
        migrations.AlterModelTable(
            name='tipofinanciamiento',
            table='catalogo_tipo_financiamiento',
        ),
        migrations.AlterModelTable(
            name='tipooperacion',
            table='catalogo_tipo_operacion',
        ),
        migrations.AlterModelTable(
            name='tipoproducto',
            table='catalogo_tipo_producto',
        ),
        migrations.AlterModelTable(
            name='tipoproyecto',
            table='catalogo_tipo_proyecto',
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='catalogo_unidad_medida',
        ),
        migrations.AlterModelTable(
            name='versioncatalogo',
            table='catalogo_version_catalogo',
        ),
        migrations.AlterModelTable(
            name='versionclasificador',
            table='catalogo_version_clasificador',
        ),
    ]
