# Generated by Django 6.0.7 on 2026-08-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_gestion_fk_gestionfiscal'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificadorinstitucional',
            options={'verbose_name': 'Clasificador institucional', 'verbose_name_plural': 'Clasificadores institucionales'},
        ),
        migrations.AlterModelOptions(
            name='entidadtransferencia',
            options={'verbose_name': 'Entidad de transferencia', 'verbose_name_plural': 'Entidades de transferencia'},
        ),
        migrations.AlterModelOptions(
            name='finalidadfuncion',
            options={'verbose_name': 'Finalidad/Función', 'verbose_name_plural': 'Finalidades y funciones'},
        ),
        migrations.AlterModelOptions(
            name='fuentefinanciamiento',
            options={'verbose_name': 'Fuente de financiamiento', 'verbose_name_plural': 'Fuentes de financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='objetogasto',
            options={'verbose_name': 'Objeto del gasto', 'verbose_name_plural': 'Objetos del gasto'},
        ),
        migrations.AlterModelOptions(
            name='organismofinanciador',
            options={'verbose_name': 'Organismo financiador', 'verbose_name_plural': 'Organismos financiadores'},
        ),
        migrations.AlterModelOptions(
            name='rubrorecurso',
            options={'verbose_name': 'Rubro de recurso', 'verbose_name_plural': 'Rubros de recursos'},
        ),
        migrations.AlterModelOptions(
            name='sectoreconomicopresupuestario',
            options={'ordering': ['codigo'], 'verbose_name': 'Sector económico presupuestario', 'verbose_name_plural': 'Sectores económicos presupuestarios'},
        ),
        migrations.AlterModelOptions(
            name='tipofinanciamiento',
            options={'verbose_name': 'Tipo de financiamiento', 'verbose_name_plural': 'Tipos de financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='tipooperacion',
            options={'verbose_name': 'Tipo de operación', 'verbose_name_plural': 'Tipos de operación'},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'verbose_name': 'Tipo de producto', 'verbose_name_plural': 'Tipos de producto'},
        ),
        migrations.AlterModelOptions(
            name='tipoproyecto',
            options={'verbose_name': 'Tipo de proyecto', 'verbose_name_plural': 'Tipos de proyecto'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.AlterModelOptions(
            name='versioncatalogo',
            options={'ordering': ['-gestion__anio', '-creado_en'], 'verbose_name': 'Versión de catálogo', 'verbose_name_plural': 'Versiones de catálogo'},
        ),
        migrations.AlterUniqueTogether(
            name='clasificadorinstitucional',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entidadtransferencia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='finalidadfuncion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='fuentefinanciamiento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='objetogasto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organismofinanciador',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rubrorecurso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sectoreconomicopresupuestario',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipofinanciamiento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipooperacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipoproducto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipoproyecto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='clasificadorinstitucional',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='entidadtransferencia',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='finalidadfuncion',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='fuentefinanciamiento',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='objetogasto',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='organismofinanciador',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='rubrorecurso',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='sectoreconomicopresupuestario',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='tipofinanciamiento',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='tipooperacion',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='versioncatalogo',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='versionclasificador',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
    ]
