# Generated by Django 6.0.7 on 2026-08-17 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_clasificadorinstitucional_options_and_more'),
        ('gestion', '0003_crear_gestiones_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorinstitucional',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clasificadores_institucionales', to='catalogos.versionclasificador'),
        ),
        migrations.AddField(
            model_name='finalidadfuncion',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalidades_funciones', to='catalogos.versionclasificador'),
        ),
        migrations.AddField(
            model_name='rubrorecurso',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubros_recurso', to='catalogos.versionclasificador'),
        ),
        migrations.AddField(
            model_name='sectoreconomicopresupuestario',
            name='version_clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectores_economicos', to='catalogos.versionclasificador'),
        ),
        migrations.AlterField(
            model_name='versionclasificador',
            name='tipo',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('rubro_recurso', 'Rubro de recurso'), ('objeto_gasto', 'Objeto del gasto'), ('finalidad_funcion', 'Finalidad/Función'), ('fuente_financiamiento', 'Fuente de financiamiento'), ('organismo_financiador', 'Organismo financiador'), ('sector_economico', 'Sector económico'), ('categoria_programatica', 'Categoría programática'), ('geografico_presupuestario', 'Geográfico presupuestario')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='clasificadorinstitucional',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_institucional_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='finalidadfuncion',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_finalidad_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='rubrorecurso',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_rubro_codigo_version'),
        ),
        migrations.AddConstraint(
            model_name='sectoreconomicopresupuestario',
            constraint=models.UniqueConstraint(condition=models.Q(('version_clasificador__isnull', False)), fields=('codigo', 'version_clasificador'), name='uniq_sector_economico_codigo_version'),
        ),
    ]
