# Generated by Django 6.0.7 on 2026-08-16 23:01
# Manual: secuencia AddField → RunPython → RemoveField → RenameField → AlterField
# (TASK PIP-DB-002): convertir gestion (año entero) → FK a GestionFiscal (UUID)
# sin pérdida de datos. La data migration mapea año → pk de GestionFiscal.anio.

import django.db.models.deletion
from django.db import migrations, models

MODELOS = (
    'AsignacionUsuarioUnidad',
    'DireccionAdministrativa',
    'UnidadEjecutora',
    'UnidadOrganizacional',
)


def mapear_gestion_anio_a_uuid(apps, schema_editor):
    GestionFiscal = apps.get_model('gestion', 'GestionFiscal')
    por_anio = {gf.anio: gf.pk for gf in GestionFiscal.objects.all()}
    for modelo in MODELOS:
        M = apps.get_model('organizacion', modelo)
        for fila in M.objects.all().order_by():
            if fila.gestion is None:
                continue
            pk = por_anio.get(int(fila.gestion))
            if pk is None:
                raise ValueError(
                    f'{modelo} {fila.pk}: gestión {fila.gestion} sin GestionFiscal '
                    f'(no se inventan gestiones — invariante PIP-DB-002).'
                )
            fila.gestion_fk_id = pk
            fila.save(update_fields=['gestion_fk'])


def revertir_gestion_uuid_a_anio(apps, schema_editor):
    GestionFiscal = apps.get_model('gestion', 'GestionFiscal')
    por_pk = {gf.pk: gf.anio for gf in GestionFiscal.objects.all()}
    for modelo in MODELOS:
        M = apps.get_model('organizacion', modelo)
        for fila in M.objects.all().order_by():
            if fila.gestion_fk_id is None:
                continue
            fila.gestion = por_pk.get(fila.gestion_fk_id)
            fila.save(update_fields=['gestion'])


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_gestionfiscal_estado'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionadministrativa',
            options={'ordering': ['gestion__anio', 'codigo'], 'verbose_name': 'Dirección Administrativa', 'verbose_name_plural': 'Direcciones Administrativas'},
        ),
        migrations.AlterModelOptions(
            name='unidadejecutora',
            options={'ordering': ['gestion__anio', 'da__codigo', 'codigo'], 'verbose_name': 'Unidad Ejecutora', 'verbose_name_plural': 'Unidades Ejecutoras'},
        ),
        migrations.AlterModelOptions(
            name='unidadorganizacional',
            options={'ordering': ['gestion__anio', 'tipo__nivel', 'orden'], 'verbose_name': 'Unidad organizacional', 'verbose_name_plural': 'Unidades organizacionales'},
        ),
        migrations.AddField(
            model_name='asignacionusuariounidad',
            name='gestion_fk',
            field=models.ForeignKey(db_column='gestion_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AddField(
            model_name='direccionadministrativa',
            name='gestion_fk',
            field=models.ForeignKey(db_column='gestion_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AddField(
            model_name='unidadejecutora',
            name='gestion_fk',
            field=models.ForeignKey(db_column='gestion_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='gestion_fk',
            field=models.ForeignKey(db_column='gestion_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.RunPython(mapear_gestion_anio_a_uuid, revertir_gestion_uuid_a_anio),
        migrations.RemoveField(
            model_name='asignacionusuariounidad',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='direccionadministrativa',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='unidadejecutora',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='gestion',
        ),
        migrations.RenameField(
            model_name='asignacionusuariounidad',
            old_name='gestion_fk',
            new_name='gestion',
        ),
        migrations.RenameField(
            model_name='direccionadministrativa',
            old_name='gestion_fk',
            new_name='gestion',
        ),
        migrations.RenameField(
            model_name='unidadejecutora',
            old_name='gestion_fk',
            new_name='gestion',
        ),
        migrations.RenameField(
            model_name='unidadorganizacional',
            old_name='gestion_fk',
            new_name='gestion',
        ),
        migrations.AlterField(
            model_name='asignacionusuariounidad',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='direccionadministrativa',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='unidadejecutora',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='gestion',
            field=models.ForeignKey(db_column='gestion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
    ]