# Generated by Django 6.0.7 on 2026-07-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('pad', '0002_resultadoterritorial_estado_articulacionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POAU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_territorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poaus', to='pad.productoterritorial')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poaus_responsable', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poaus', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'POAU',
                'verbose_name_plural': 'POAUs',
                'ordering': ['gestion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='POAUActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('meta_fisica_anual', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('presupuesto_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('objeto_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.objetogasto')),
                ('poau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='poau.poau')),
            ],
            options={
                'verbose_name': 'Actividad POAU',
                'verbose_name_plural': 'Actividades POAU',
                'ordering': ['poau', 'codigo'],
                'unique_together': {('poau', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: 2026-01, 2026-Q1, 2026-S1, 2026', max_length=20)),
                ('tipo_periodo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10)),
                ('programado', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('ejecutado', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecucion_fisica', to='poau.poauactividad')),
            ],
            options={
                'verbose_name': 'Ejecución física',
                'verbose_name_plural': 'Ejecuciones físicas',
                'ordering': ['periodo'],
                'unique_together': {('actividad', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: 2026-01, 2026-Q1, 2026-S1, 2026', max_length=20)),
                ('tipo_periodo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=10)),
                ('programado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecucion_financiera', to='poau.poauactividad')),
            ],
            options={
                'verbose_name': 'Ejecución financiera',
                'verbose_name_plural': 'Ejecuciones financieras',
                'ordering': ['periodo'],
                'unique_together': {('actividad', 'periodo')},
            },
        ),
    ]
