# Generated by Django 6.0.7 on 2026-07-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_alter_nodoplanificacion_nivel_sector'),
        ('poau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poauactividad',
            name='accion_corto_plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_poau', to='planificacion.accioncortoplazo', verbose_name='Acción de Corto Plazo'),
        ),
        migrations.AddField(
            model_name='poauactividad',
            name='meta_q1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Meta Q1'),
        ),
        migrations.AddField(
            model_name='poauactividad',
            name='meta_q2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Meta Q2'),
        ),
        migrations.AddField(
            model_name='poauactividad',
            name='meta_q3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Meta Q3'),
        ),
        migrations.AddField(
            model_name='poauactividad',
            name='meta_q4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Meta Q4'),
        ),
    ]
