# Generated by Django 6.0.7 on 2026-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_nodoestrategico_planificaci_version_0c0b75_idx_and_more'),
        ('poau', '0003_accioncortoplazo_operacion_actividad_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poainstitucional',
            index=models.Index(fields=['gestion', 'estado'], name='poau_poains_gestion_0ac185_idx'),
        ),
    ]
