# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('poau', '0002_poauactividad_accion_corto_plazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSeguimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestion')),
                ('periodo', models.CharField(help_text='Formato: 2026-Q1, 2026-S1, 2026', max_length=20, verbose_name='Periodo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('validado', 'Validado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envio')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobacion')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('unidad_organizacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_seguimiento', to='organizacion.unidadorganizacional', verbose_name='Unidad Organizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de seguimiento',
                'verbose_name_plural': 'Reportes de seguimiento',
                'ordering': ['-gestion', '-periodo'],
            },
        ),
        migrations.CreateModel(
            name='EntradaSeguimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programado_fisico', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Programado fisico')),
                ('ejecutado_fisico', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Ejecutado fisico')),
                ('porcentaje_avance_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% Avance fisico')),
                ('presupuesto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Presupuesto inicial')),
                ('presupuesto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Presupuesto actual')),
                ('programado_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Programado financiero')),
                ('ejecutado_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ejecutado financiero')),
                ('porcentaje_avance_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% Avance financiero')),
                ('desviacion', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Desviacion (%)')),
                ('causa_desviacion', models.TextField(blank=True, default='', verbose_name='Causa de desviacion')),
                ('accion_correctiva', models.TextField(blank=True, null=True, verbose_name='Accion correctiva')),
                ('proyeccion_cierre', models.TextField(blank=True, default='', verbose_name='Proyeccion a fin de gestion')),
                ('evidencia', models.TextField(blank=True, default='', verbose_name='Evidencia')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_seguimiento', to='poau.poauactividad', verbose_name='Actividad')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='seguimiento.reporteseguimiento', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Entrada de seguimiento',
                'verbose_name_plural': 'Entradas de seguimiento',
                'ordering': ['actividad__codigo'],
            },
        ),
        migrations.CreateModel(
            name='UmbralConfiguracion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_umbral', models.CharField(choices=[('ejecucion_fisica_baja', 'Ejecucion fisica baja'), ('ejecucion_financiera_baja', 'Ejecucion financiera baja'), ('avance_sin_financiera', 'Avance sin financiamiento'), ('financiera_sin_avance', 'Financiamiento sin avance'), ('sobreejecucion', 'Sobreejecucion'), ('meta_vencida', 'Meta vencida'), ('sin_evidencia', 'Sin evidencia'), ('incumplimiento_correctivo', 'Incumplimiento de accion correctiva'), ('presupuesto_sin_actividad', 'Presupuesto sin actividad'), ('actividad_sin_presupuesto', 'Actividad sin presupuesto')], max_length=40, unique=True, verbose_name='Tipo de umbral')),
                ('porcentaje_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Porcentaje minimo')),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='Porcentaje maximo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umbral de configuracion',
                'verbose_name_plural': 'Umbrales de configuracion',
                'ordering': ['tipo_umbral'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ejecucion_fisica_baja', 'Ejecucion fisica baja'), ('ejecucion_financiera_baja', 'Ejecucion financiera baja'), ('avance_sin_financiera', 'Avance sin financiamiento'), ('financiera_sin_avance', 'Financiamiento sin avance'), ('sobreejecucion', 'Sobreejecucion'), ('meta_vencida', 'Meta vencida'), ('sin_evidencia', 'Sin evidencia'), ('incumplimiento_correctivo', 'Incumplimiento de accion correctiva'), ('presupuesto_sin_actividad', 'Presupuesto sin actividad'), ('actividad_sin_presupuesto', 'Actividad sin presupuesto')], max_length=40, verbose_name='Tipo de alerta')),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='leve', max_length=10, verbose_name='Severidad')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='seguimiento.entradaseguimiento', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activa', 'tipo'], name='seguimiento_activa_ab9662_idx'), models.Index(fields=['severidad'], name='seguimiento_severid_7dc766_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reporteseguimiento',
            index=models.Index(fields=['gestion', 'periodo'], name='seguimiento_gestion_82a922_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteseguimiento',
            index=models.Index(fields=['estado'], name='seguimiento_estado_1305d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporteseguimiento',
            unique_together={('gestion', 'periodo', 'unidad_organizacional')},
        ),
        migrations.AddIndex(
            model_name='entradaseguimiento',
            index=models.Index(fields=['reporte', 'actividad'], name='seguimiento_reporte_521f0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entradaseguimiento',
            unique_together={('reporte', 'actividad')},
        ),
    ]
