# Generated by Django 6.0.7 on 2026-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entradaseguimiento',
            name='seguimiento_reporte_521f0b_idx',
        ),
    ]
