# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poau', '0002_poauactividad_accion_corto_plazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudModificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('meta', 'Modificación de Meta'), ('operacion', 'Modificación de Operación'), ('reprogramacion', 'Reprogramación'), ('responsable', 'Cambio de Responsable'), ('inscripcion', 'Inscripción'), ('eliminacion', 'Eliminación'), ('incremento', 'Incremento Presupuestario'), ('reduccion', 'Reducción Presupuestaria'), ('traspaso', 'Traspaso Presupuestario'), ('fuente', 'Cambio de Fuente de Financiamiento'), ('organismo', 'Cambio de Organismo Financiador'), ('categoria', 'Cambio de Categoría'), ('reformulacion', 'Reformulación')], max_length=20, verbose_name='Tipo de modificación')),
                ('gestion_fiscal', models.PositiveIntegerField(verbose_name='Gestión fiscal')),
                ('entidad_afectada_tipo', models.CharField(help_text='Nombre del modelo ContentType de la entidad afectada', max_length=100, verbose_name='Tipo de entidad afectada')),
                ('entidad_afectada_id', models.UUIDField(verbose_name='ID de entidad afectada')),
                ('motivo', models.TextField(verbose_name='Motivo de la modificación')),
                ('informe_tecnico', models.TextField(blank=True, verbose_name='Informe técnico')),
                ('documento_legal', models.TextField(blank=True, verbose_name='Documento legal / respaldo normativo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cumplida', 'Cumplida')], default='borrador', max_length=15)),
                ('fecha_efectiva', models.DateField(blank=True, null=True, verbose_name='Fecha efectiva')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('poau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_modificacion', to='poau.poau', verbose_name='POAU')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_modificacion', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de modificación',
                'verbose_name_plural': 'Solicitudes de modificación',
                'ordering': ['-created_at', 'gestion_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='ImpactoModificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impacto_fisico', models.TextField(blank=True, verbose_name='Impacto físico')),
                ('impacto_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impacto financiero')),
                ('impacto_estrategico', models.TextField(blank=True, verbose_name='Impacto estratégico')),
                ('documento_aprobacion', models.TextField(blank=True, verbose_name='Documento de aprobación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impacto', to='modificaciones.solicitudmodificacion')),
            ],
            options={
                'verbose_name': 'Impacto de modificación',
                'verbose_name_plural': 'Impactos de modificación',
            },
        ),
        migrations.CreateModel(
            name='CambioModificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campo', models.CharField(max_length=200, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_propuesto', models.TextField(blank=True, verbose_name='Valor propuesto')),
                ('valor_aprobado', models.TextField(blank=True, null=True, verbose_name='Valor aprobado')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='modificaciones.solicitudmodificacion')),
            ],
            options={
                'verbose_name': 'Cambio de modificación',
                'verbose_name_plural': 'Cambios de modificación',
                'ordering': ['solicitud', 'campo'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudmodificacion',
            index=models.Index(fields=['gestion_fiscal', 'estado'], name='modificacio_gestion_8f302e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudmodificacion',
            index=models.Index(fields=['entidad_afectada_tipo', 'entidad_afectada_id'], name='modificacio_entidad_c968ae_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudmodificacion',
            index=models.Index(fields=['tipo', 'estado'], name='modificacio_tipo_4db8be_idx'),
        ),
    ]
