# Generated by Django 6.0.7 on 2026-07-15 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear', 'Creación'), ('modificar', 'Modificación'), ('anular', 'Anulación'), ('restaurar', 'Restauración'), ('enviar', 'Envío'), ('devolver', 'Devolución'), ('aprobar', 'Aprobación'), ('reabrir', 'Reapertura'), ('importar', 'Importación'), ('exportar', 'Exportación'), ('consolidar', 'Consolidación'), ('cerrar', 'Cierre')], max_length=20)),
                ('entidad', models.CharField(help_text='Nombre del modelo', max_length=100)),
                ('entidad_id', models.CharField(help_text='ID del registro afectado', max_length=100)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, help_text='Descripción del cambio')),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_posteriores', models.JSONField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('gestion', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='auditoria_e_entidad_0d3762_idx'), models.Index(fields=['usuario', 'creado_en'], name='auditoria_e_usuario_579fe3_idx'), models.Index(fields=['gestion'], name='auditoria_e_gestion_b05570_idx')],
            },
        ),
    ]
