# Generated by Django 6.0.7 on 2026-08-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear', 'Creación'), ('modificar', 'Modificación'), ('anular', 'Anulación'), ('restaurar', 'Restauración'), ('enviar', 'Envío'), ('devolver', 'Devolución'), ('aprobar', 'Aprobación'), ('reabrir', 'Reapertura'), ('importar', 'Importación'), ('exportar', 'Exportación'), ('consolidar', 'Consolidación'), ('cerrar', 'Cierre'), ('distribucion', 'Distribución'), ('redistribucion', 'Redistribución'), ('reserva', 'Reserva'), ('liberacion', 'Liberación'), ('reversion', 'Reversión'), ('ajuste', 'Ajuste'), ('conciliar', 'Conciliación'), ('activar', 'Activación')], max_length=20),
        ),
    ]
