# Generated by Django 6.0.7 on 2026-08-15 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['entidad', 'entidad_id', '-creado_en'], name='audit_entidad_historial_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['gestion', 'accion'], name='audit_gestion_accion_idx'),
        ),
    ]
