# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioFormulacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_formulacion', to='organizacion.unidadorganizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío de formulación',
                'verbose_name_plural': 'Envíos de formulación',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_revision', models.CharField(choices=[('planificacion', 'Planificación'), ('presupuesto', 'Presupuesto'), ('inversion', 'Proyectos e Inversión'), ('juridica', 'Jurídica')], max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('devuelta', 'Devuelta')], default='pendiente', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=20, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='workflow.envioformulacion')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('forma', 'Forma'), ('fondo', 'Fondo'), ('legal', 'Legal'), ('presupuestaria', 'Presupuestaria'), ('tecnica', 'Técnica'), ('documental', 'Documental')], max_length=20)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='moderada', max_length=20)),
                ('modulo', models.CharField(help_text='Módulo afectado (ej: indicadores, presupuesto)', max_length=50)),
                ('registro_id', models.CharField(help_text='ID del registro afectado', max_length=100)),
                ('texto', models.TextField()),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('respondida', 'Respondida'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('evidencia_subsanacion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable_subsanacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='workflow.revision')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('unidad', 'Aprobación de unidad'), ('planificacion', 'Validación de Planificación'), ('presupuesto', 'Validación de Presupuesto'), ('consolidacion', 'Consolidación institucional'), ('control_social', 'Pronunciamiento Control Social'), ('mae', 'Aprobación MAE'), ('concejo', 'Aprobación Concejo Municipal')], max_length=50)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField()),
                ('huella_documento', models.CharField(blank=True, help_text='SHA-256 del documento aprobado', max_length=64)),
                ('es_reapertura', models.BooleanField(default=False)),
                ('motivo_reapertura', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones', to='documentos.documentoadjunto')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobación',
                'verbose_name_plural': 'Aprobaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gestion', 'tipo', 'version'], name='workflow_ap_gestion_6a6333_idx')],
            },
        ),
    ]
