# Generated by Django 6.0.7 on 2026-08-09 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# =============================================================================
# Seed base (WP-08): definición 'validacion_instrumento' con los estados del
# kernel estratégico (plan maestro §19.2). Idempotente.
# =============================================================================
PASOS_VALIDACION = [
    (1, 'Borrador', 'borrador', True, False),
    (2, 'En formulación', 'en_formulacion', False, False),
    (3, 'En revisión', 'en_revision', False, False),
    (4, 'Validado', 'validado', False, False),
    (5, 'Aprobado', 'aprobado', False, True),
]

TRANSICIONES_VALIDACION = [
    (None, 2, 'Enviar a formulación', ['sis_pe.instrumento.create'], False),
    (2, 3, 'Enviar a revisión', ['sis_pe.pad.edit', 'sis_pe.pei.edit'], False),
    (3, 4, 'Validar', ['sis_pe.pad.validate'], False),
    (4, 5, 'Aprobar', ['sis_pe.approve'], True),
]


def seed_definiciones(apps, schema_editor):
    Definition = apps.get_model('workflow', 'WorkflowDefinition')
    Step = apps.get_model('workflow', 'WorkflowStepDefinition')
    Transition = apps.get_model('workflow', 'WorkflowTransition')

    definicion, _ = Definition.objects.get_or_create(
        codigo='validacion_instrumento',
        defaults={
            'nombre': 'Validación de instrumento estratégico',
            'tipo_entidad': 'VersionInstrumento',
            'descripcion': (
                'Flujo de validación y aprobación de versiones de '
                'instrumentos de planificación (kernel SIS-PE).'
            ),
        },
    )
    pasos = {}
    for orden, nombre, estado, inicial, final in PASOS_VALIDACION:
        paso, _ = Step.objects.get_or_create(
            definicion=definicion, orden=orden,
            defaults={
                'nombre': nombre,
                'estado': estado,
                'es_inicial': inicial,
                'es_final': final,
            },
        )
        pasos[orden] = paso

    for desde, hacia, nombre, capacidades, requiere_aprob in TRANSICIONES_VALIDACION:
        Transition.objects.get_or_create(
            definicion=definicion,
            desde_paso=pasos[desde] if desde else None,
            hacia_paso=pasos[hacia],
            defaults={
                'nombre': nombre,
                'capacidades_requeridas': capacidades,
                'requiere_aprobacion': requiere_aprob,
            },
        )
class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_entidad', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definición de workflow',
                'verbose_name_plural': 'Definiciones de workflow',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Paso de workflow',
                'verbose_name_plural': 'Pasos de workflow',
                'ordering': ['definicion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidad_tipo', models.CharField(max_length=50)),
                ('entidad_id', models.UUIDField()),
                ('estado_actual', models.CharField(max_length=50)),
                ('cerrado', models.BooleanField(default=False)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='workflow.workflowdefinition')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_iniciados', to=settings.AUTH_USER_MODEL)),
                ('paso_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_en_paso', to='workflow.workflowstepdefinition')),
            ],
            options={
                'verbose_name': 'Instancia de workflow',
                'verbose_name_plural': 'Instancias de workflow',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_workflow', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='workflow.workflowinstance')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='workflow.workflowstepdefinition')),
            ],
            options={
                'verbose_name': 'Tarea de workflow',
                'verbose_name_plural': 'Tareas de workflow',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowObservacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('bloqueante', 'Bloqueante')], default='moderada', max_length=20)),
                ('resuelta', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='workflow.workflowinstance')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_workflow', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='workflow.workflowtask')),
            ],
            options={
                'verbose_name': 'Observación de workflow',
                'verbose_name_plural': 'Observaciones de workflow',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_workflow', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='workflow.workflowinstance')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones', to='workflow.workflowtask')),
            ],
            options={
                'verbose_name': 'Aprobación de workflow',
                'verbose_name_plural': 'Aprobaciones de workflow',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('delegado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('delegado_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones', to='workflow.workflowtask')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('capacidades_requeridas', models.JSONField(blank=True, default=list)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='workflow.workflowdefinition')),
                ('desde_paso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salientes', to='workflow.workflowstepdefinition')),
                ('hacia_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrantes', to='workflow.workflowstepdefinition')),
            ],
            options={
                'verbose_name': 'Transición de workflow',
                'verbose_name_plural': 'Transiciones de workflow',
                'ordering': ['definicion', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstepdefinition',
            constraint=models.UniqueConstraint(fields=('definicion', 'orden'), name='uniq_paso_workflow_orden'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrado', False)), fields=('definicion', 'entidad_tipo', 'entidad_id'), name='uniq_instancia_abierta_por_entidad'),
        ),
        migrations.RunPython(seed_definiciones, migrations.RunPython.noop),
    ]

