# Generated by Django 6.0.7 on 2026-08-10 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowdefinition_workflowstepdefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['entidad_tipo', 'entidad_id'], name='workflow_wo_entidad_2bbe9b_idx'),
        ),
    ]
