# Generated by Django 6.0.7 on 2026-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowinstance_workflow_wo_entidad_2bbe9b_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aprobacion',
            new_name='flujo_aprob_gestion_5bbd7f_idx',
            old_name='workflow_ap_gestion_6a6333_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='flujo_insta_entidad_ce77cf_idx',
            old_name='workflow_wo_entidad_2bbe9b_idx',
        ),
        migrations.AlterModelTable(
            name='aprobacion',
            table='flujo_aprobacion',
        ),
        migrations.AlterModelTable(
            name='delegacion',
            table='flujo_delegacion',
        ),
        migrations.AlterModelTable(
            name='envioformulacion',
            table='flujo_envio_formulacion',
        ),
        migrations.AlterModelTable(
            name='observacion',
            table='flujo_observacion',
        ),
        migrations.AlterModelTable(
            name='revision',
            table='flujo_revision',
        ),
        migrations.AlterModelTable(
            name='workflowaprobacion',
            table='flujo_aprobacion_motor',
        ),
        migrations.AlterModelTable(
            name='workflowdefinition',
            table='flujo_definicion',
        ),
        migrations.AlterModelTable(
            name='workflowinstance',
            table='flujo_instancia',
        ),
        migrations.AlterModelTable(
            name='workflowobservacion',
            table='flujo_observacion_motor',
        ),
        migrations.AlterModelTable(
            name='workflowstepdefinition',
            table='flujo_paso_definicion',
        ),
        migrations.AlterModelTable(
            name='workflowtask',
            table='flujo_tarea',
        ),
        migrations.AlterModelTable(
            name='workflowtransition',
            table='flujo_transicion',
        ),
    ]
