# Generated by Django 6.0.7 on 2026-08-15 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_rename_workflow_ap_gestion_6a6333_idx_flujo_aprob_gestion_5bbd7f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(condition=models.Q(('estado__in', ['pendiente', 'en_curso'])), fields=['asignado_a', '-creado_en'], name='flujo_tarea_bandeja_idx'),
        ),
    ]
