# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoPlanificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('eje', 'Eje Estratégico'), ('meta', 'Meta'), ('resultado', 'Resultado'), ('accion_nacional', 'Acción Nacional'), ('accion_mediano', 'Acción de Mediano Plazo'), ('accion_corto', 'Acción de Corto Plazo'), ('operacion', 'Operación'), ('tarea', 'Tarea')], max_length=30)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='planificacion.nodoplanificacion')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nodo de planificación',
                'verbose_name_plural': 'Nodos de planificación',
                'ordering': ['plan', 'nivel', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='AccionMedianoPlazo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('gestion_inicio', models.PositiveIntegerField()),
                ('gestion_fin', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_mediano_plazo', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nodo_planificacion', models.ForeignKey(limit_choices_to={'nivel': 'accion_mediano'}, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_mediano_plazo', to='planificacion.nodoplanificacion')),
            ],
            options={
                'verbose_name': 'Acción de mediano plazo',
                'verbose_name_plural': 'Acciones de mediano plazo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('pdes', 'PDES'), ('ptdi', 'PTDI'), ('pei', 'PEI'), ('sectorial', 'Plan Sectorial'), ('municipal', 'Plan Municipal'), ('otro', 'Otro')], max_length=50)),
                ('gestion_inicio', models.PositiveIntegerField()),
                ('gestion_fin', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['tipo', 'gestion_inicio'],
                'unique_together': {('codigo', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='nodoplanificacion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='planificacion.plan'),
        ),
        migrations.CreateModel(
            name='AccionCortoPlazo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('justificacion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidad_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_corto_plazo', to='organizacion.unidadorganizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('accion_mediano_plazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_corto_plazo', to='planificacion.accionmedianoplazo')),
            ],
            options={
                'verbose_name': 'Acción de corto plazo',
                'verbose_name_plural': 'Acciones de corto plazo',
                'ordering': ['gestion', 'codigo'],
                'unique_together': {('codigo', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='ArticulacionPlanificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('gestion', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulaciones_entrada', to='planificacion.nodoplanificacion')),
                ('nodo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulaciones_salida', to='planificacion.nodoplanificacion')),
            ],
            options={
                'verbose_name': 'Articulación de planificación',
                'verbose_name_plural': 'Articulaciones de planificación',
                'unique_together': {('nodo_origen', 'nodo_destino', 'gestion')},
            },
        ),
        migrations.AddIndex(
            model_name='nodoplanificacion',
            index=models.Index(fields=['nivel', 'gestion'], name='planificaci_nivel_1d8e17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodoplanificacion',
            unique_together={('plan', 'codigo', 'nivel')},
        ),
    ]
