# Generated by Django 6.0.7 on 2026-07-15 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoplanificacion',
            name='nivel',
            field=models.CharField(choices=[('pilar', 'Pilar'), ('eje', 'Eje Estratégico'), ('meta', 'Meta'), ('resultado', 'Resultado'), ('accion_nacional', 'Acción Nacional'), ('accion_pdes', 'Acción PDES/PTDI/PEI'), ('accion_mediano', 'Acción de Mediano Plazo'), ('accion_corto', 'Acción de Corto Plazo'), ('operacion', 'Operación'), ('tarea', 'Tarea')], max_length=30),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['codigo'],
            },
        ),
    ]
