# Generated by Django 6.0.7 on 2026-07-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_planversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoplanificacion',
            name='nivel',
            field=models.CharField(choices=[('pilar', 'Pilar'), ('eje', 'Eje Estratégico'), ('meta', 'Meta'), ('resultado', 'Resultado'), ('componente', 'Componente'), ('accion', 'Acción'), ('accion_nacional', 'Acción Nacional'), ('accion_pdes', 'Acción PDES/PTDI/PEI'), ('accion_mediano', 'Acción de Mediano Plazo'), ('accion_corto', 'Acción de Corto Plazo'), ('operacion', 'Operación'), ('tarea', 'Tarea')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tipo',
            field=models.CharField(choices=[('pdes', 'PDES'), ('ptdi', 'PTDI'), ('pgdesa', 'PGDESA'), ('pdesa', 'PDESA'), ('pei', 'PEI'), ('sectorial', 'Plan Sectorial'), ('municipal', 'Plan Municipal'), ('otro', 'Otro')], max_length=50),
        ),
    ]
