# Generated by Django 6.0.7 on 2026-08-09 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_nodoplanificacion_nivel_alter_plan_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('nacional', 'Nacional'), ('sectorial', 'Sectorial'), ('territorial', 'Territorial'), ('institucional', 'Institucional'), ('operativo', 'Operativo')], max_length=20)),
                ('horizonte_anios', models.PositiveIntegerField(blank=True, null=True)),
                ('entidad_emisora', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de instrumento',
                'verbose_name_plural': 'Tipos de instrumento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoNodoEstrategico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('denominacion', models.CharField(max_length=200)),
                ('nivel_orden', models.PositiveIntegerField(default=1)),
                ('permite_hijos', models.BooleanField(default=True)),
                ('cardinalidad', models.CharField(choices=[('uno', 'Uno'), ('muchos', 'Muchos')], default='muchos', max_length=20)),
                ('reglas_codigo', models.CharField(blank=True, default='', max_length=200)),
                ('campos_obligatorios', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de nodo estratégico',
                'verbose_name_plural': 'Tipos de nodo estratégico',
                'ordering': ['metodologia', 'nivel_orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoPlanificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('institucion_responsable', models.CharField(blank=True, default='', max_length=300)),
                ('periodo_inicio', models.PositiveIntegerField()),
                ('periodo_fin', models.PositiveIntegerField()),
                ('ambito', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_formulacion', 'En formulación'), ('en_revision', 'En revisión'), ('observado', 'Observado'), ('validado', 'Validado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='planificacion.tipoinstrumento')),
            ],
            options={
                'verbose_name': 'Instrumento de planificación',
                'verbose_name_plural': 'Instrumentos de planificación',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='VersionInstrumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_formulacion', 'En formulación'), ('en_revision', 'En revisión'), ('observado', 'Observado'), ('validado', 'Validado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('inmutable', models.BooleanField(default=False)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('norma_aprobacion', models.CharField(blank=True, default='', max_length=300)),
                ('motivo_cambio', models.TextField(blank=True, default='')),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='planificacion.instrumentoplanificacion')),
            ],
            options={
                'verbose_name': 'Versión de instrumento',
                'verbose_name_plural': 'Versiones de instrumento',
                'ordering': ['instrumento', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='NodoEstrategico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='planificacion.nodoestrategico')),
                ('tipo_nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodos', to='planificacion.tiponodoestrategico')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='planificacion.versioninstrumento')),
            ],
            options={
                'verbose_name': 'Nodo estratégico',
                'verbose_name_plural': 'Nodos estratégicos',
                'ordering': ['version', 'orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='VersionMetodologia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('fuente_oficial', models.CharField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('vigente', 'Vigente'), ('deprecada', 'Deprecada'), ('retirada', 'Retirada')], default='borrador', max_length=20)),
                ('esquema_validacion', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metodologias', to='planificacion.tipoinstrumento')),
            ],
            options={
                'verbose_name': 'Versión de metodología',
                'verbose_name_plural': 'Versiones de metodología',
                'ordering': ['tipo_instrumento', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='versioninstrumento',
            name='metodologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_instrumento', to='planificacion.versionmetodologia'),
        ),
        migrations.CreateModel(
            name='TipoVinculoEstrategico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('denominacion', models.CharField(max_length=200)),
                ('requiere_ponderacion', models.BooleanField(default=False)),
                ('requiere_justificacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('destino_permitido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_destino', to='planificacion.tiponodoestrategico')),
                ('origen_permitido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_origen', to='planificacion.tiponodoestrategico')),
                ('metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_vinculo', to='planificacion.versionmetodologia')),
            ],
            options={
                'verbose_name': 'Tipo de vínculo estratégico',
                'verbose_name_plural': 'Tipos de vínculo estratégico',
                'ordering': ['metodologia', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='tiponodoestrategico',
            name='metodologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_nodo', to='planificacion.versionmetodologia'),
        ),
        migrations.CreateModel(
            name='VinculoEstrategico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('ponderacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_destino', to='planificacion.nodoestrategico')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_origen', to='planificacion.nodoestrategico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='planificacion.tipovinculoestrategico')),
                ('validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_validados', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='planificacion.versioninstrumento')),
            ],
            options={
                'verbose_name': 'Vínculo estratégico',
                'verbose_name_plural': 'Vínculos estratégicos',
                'ordering': ['version', 'origen', 'destino'],
            },
        ),
        migrations.AddConstraint(
            model_name='nodoestrategico',
            constraint=models.UniqueConstraint(fields=('version', 'codigo'), name='uniq_nodo_version_codigo'),
        ),
        migrations.AddConstraint(
            model_name='versioninstrumento',
            constraint=models.UniqueConstraint(fields=('instrumento', 'numero'), name='uniq_version_instrumento_numero'),
        ),
        migrations.AddConstraint(
            model_name='tipovinculoestrategico',
            constraint=models.UniqueConstraint(fields=('metodologia', 'codigo'), name='uniq_tipo_vinculo_metodologia_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tiponodoestrategico',
            constraint=models.UniqueConstraint(fields=('metodologia', 'codigo'), name='uniq_tipo_nodo_metodologia_codigo'),
        ),
        migrations.AddConstraint(
            model_name='vinculoestrategico',
            constraint=models.UniqueConstraint(fields=('version', 'origen', 'destino', 'tipo'), name='uniq_vinculo_version_origen_destino_tipo'),
        ),
    ]
