# Generated by Django 6.0.7 on 2026-08-10 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_tipoinstrumento_tiponodoestrategico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nodoestrategico',
            index=models.Index(fields=['version', 'tipo_nodo'], name='planificaci_version_0c0b75_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoestrategico',
            index=models.Index(fields=['version', 'destino'], name='planificaci_version_36d4c2_idx'),
        ),
    ]
