# Generated by Django 6.0.7 on 2026-08-17 20:36

from django.db import migrations


class Migration(migrations.Migration):
    """Retires the V2 strategic kernel, which is under construction (BETA).

    The eight tables backing the SIS-PE tools were empty and every external FK
    into them was unpopulated. The kernel is rebuilt progressively, one tool at
    a time, so the schema does not carry structure ahead of its domain.
    """


    dependencies = [
        ('planificacion', '0006_nodoestrategico_planificaci_version_0c0b75_idx_and_more'),
        ('poau', '0006_remove_kernel_v2_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentoplanificacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='instrumentoplanificacion',
            name='tipo',
        ),
        migrations.RemoveIndex(
            model_name='nodoestrategico',
            name='planificaci_version_0c0b75_idx',
        ),
        migrations.RemoveConstraint(
            model_name='nodoestrategico',
            name='uniq_nodo_version_codigo',
        ),
        migrations.RemoveField(
            model_name='versionmetodologia',
            name='tipo_instrumento',
        ),
        migrations.RemoveConstraint(
            model_name='tiponodoestrategico',
            name='uniq_tipo_nodo_metodologia_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='tipovinculoestrategico',
            name='uniq_tipo_vinculo_metodologia_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='versioninstrumento',
            name='uniq_version_instrumento_numero',
        ),
        migrations.RemoveIndex(
            model_name='vinculoestrategico',
            name='planificaci_version_36d4c2_idx',
        ),
        migrations.RemoveConstraint(
            model_name='vinculoestrategico',
            name='uniq_vinculo_version_origen_destino_tipo',
        ),
        migrations.RemoveField(
            model_name='nodoestrategico',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='nodoestrategico',
            name='tipo_nodo',
        ),
        migrations.RemoveField(
            model_name='nodoestrategico',
            name='version',
        ),
        migrations.DeleteModel(
            name='TipoInstrumento',
        ),
        migrations.RemoveField(
            model_name='tipovinculoestrategico',
            name='destino_permitido',
        ),
        migrations.RemoveField(
            model_name='tipovinculoestrategico',
            name='metodologia',
        ),
        migrations.RemoveField(
            model_name='tipovinculoestrategico',
            name='origen_permitido',
        ),
        migrations.RemoveField(
            model_name='versioninstrumento',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='versioninstrumento',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='versioninstrumento',
            name='metodologia',
        ),
        migrations.RemoveField(
            model_name='vinculoestrategico',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='vinculoestrategico',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='vinculoestrategico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='vinculoestrategico',
            name='validador',
        ),
        migrations.RemoveField(
            model_name='vinculoestrategico',
            name='version',
        ),
        migrations.DeleteModel(
            name='TipoNodoEstrategico',
        ),
        migrations.DeleteModel(
            name='InstrumentoPlanificacion',
        ),
        migrations.DeleteModel(
            name='VersionMetodologia',
        ),
        migrations.DeleteModel(
            name='NodoEstrategico',
        ),
        migrations.DeleteModel(
            name='TipoVinculoEstrategico',
        ),
        migrations.DeleteModel(
            name='VersionInstrumento',
        ),
        migrations.DeleteModel(
            name='VinculoEstrategico',
        ),
    ]
