# Generated by Django 6.0.7 on 2026-07-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política PAD',
                'verbose_name_plural': 'Políticas PAD',
                'ordering': ['gestion', 'codigo'],
                'unique_together': {('codigo', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='LineamientoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=500)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineamientos', to='pad.politicapad')),
            ],
            options={
                'verbose_name': 'Lineamiento estratégico',
                'verbose_name_plural': 'Lineamientos estratégicos',
                'ordering': ['gestion', 'codigo'],
                'unique_together': {('codigo', 'politica', 'gestion')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('indicador', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('linea_base', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('meta_2030', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('programacion_fisica', models.JSONField(blank=True, help_text='Programación física por gestión: {"2026": valor, "2027": valor, ...}', null=True)),
                ('programacion_financiera', models.JSONField(blank=True, help_text='Programación financiera por gestión: {"2026": monto, ...}', null=True)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lineamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='pad.lineamientoestrategico')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado territorial',
                'verbose_name_plural': 'Resultados territoriales',
                'ordering': ['gestion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ArticulacionSIPEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_eje_pgdesa', models.CharField(blank=True, help_text='7 ejes del PGDESA', max_length=20, verbose_name='Código Eje PGDESA')),
                ('objetivo_impacto_pgdesa', models.TextField(blank=True, verbose_name='Objetivo de impacto PGDESA')),
                ('cod_componente_pdesa', models.CharField(blank=True, max_length=20, verbose_name='Código Componente PDESA')),
                ('objetivo_efecto_pdesa', models.TextField(blank=True, verbose_name='Objetivo de efecto PDESA')),
                ('cod_ods', models.CharField(blank=True, help_text='17 Objetivos de Desarrollo Sostenible', max_length=10, verbose_name='Código ODS')),
                ('cod_meta_ndc', models.CharField(blank=True, help_text='35 metas de la Contribución Nacional Determinada', max_length=10, verbose_name='Código Meta NDC')),
                ('cod_principio_ndt', models.CharField(blank=True, help_text='19 principios del Nuevo Trato Departamental', max_length=10, verbose_name='Código Principio NDT')),
                ('compromisos_3030', models.TextField(blank=True, help_text='Iniciativa 30x30 (áreas protegidas)', verbose_name='Compromisos 30x30')),
                ('cod_sector', models.CharField(blank=True, max_length=10, verbose_name='Código Sector')),
                ('sector_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Sector')),
                ('cod_resultado_pds', models.CharField(blank=True, max_length=20, verbose_name='Código Resultado PDS')),
                ('resultado_pds', models.TextField(blank=True, verbose_name='Resultado PDS')),
                ('cod_geografico', models.CharField(blank=True, max_length=20, verbose_name='Código Geográfico')),
                ('denominacion_eta', models.CharField(blank=True, help_text='Entidad Territorial Autónoma (GAM Sacaba)', max_length=300, verbose_name='Denominación ETA')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='articulacion_sipeb', to='pad.resultadoterritorial')),
            ],
            options={
                'verbose_name': 'Articulación SIPEB',
                'verbose_name_plural': 'Articulaciones SIPEB',
                'ordering': ['gestion', 'resultado'],
            },
        ),
        migrations.CreateModel(
            name='SectorPAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sector PAD',
                'verbose_name_plural': 'Sectores PAD',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='resultadoterritorial',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='pad.sectorpad'),
        ),
        migrations.CreateModel(
            name='ProductoTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('territorializacion', models.TextField(blank=True, help_text='Ámbito territorial del producto')),
                ('responsable', models.CharField(blank=True, help_text='Unidad/instancia responsable', max_length=300)),
                ('indicador', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True)),
                ('linea_base', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('meta_2030', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('programacion_fisica', models.JSONField(blank=True, help_text='Programación física por gestión: {"2026": valor, "2027": valor, ...}', null=True)),
                ('programacion_financiera', models.JSONField(blank=True, help_text='Programación financiera por gestión: {"2026": monto, ...}', null=True)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pad.resultadoterritorial')),
            ],
            options={
                'verbose_name': 'Producto territorial',
                'verbose_name_plural': 'Productos territoriales',
                'ordering': ['gestion', 'codigo'],
                'unique_together': {('codigo', 'resultado', 'gestion')},
            },
        ),
        migrations.AddIndex(
            model_name='resultadoterritorial',
            index=models.Index(fields=['gestion', 'lineamiento'], name='pad_resulta_gestion_676129_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadoterritorial',
            unique_together={('codigo', 'lineamiento', 'gestion')},
        ),
    ]
