# Generated by Django 6.0.7 on 2026-07-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoterritorial',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado para aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado con observaciones')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ArticulacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(help_text="Nombre del modelo: 'resultado', 'producto'", max_length=50)),
                ('entidad_id', models.CharField(max_length=100)),
                ('accion', models.CharField(help_text="Acción: 'crear', 'modificar', 'enviar', 'aprobar', 'rechazar'", max_length=50)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de articulación',
                'verbose_name_plural': 'Logs de articulación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
