# Generated by Django 6.0.7 on 2026-07-16 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0002_resultadoterritorial_estado_articulacionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productoterritorial',
            name='cuenta_con_financiamiento',
            field=models.CharField(choices=[('SI', 'SÍ'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Cuenta con financiamiento'),
        ),
        migrations.AddField(
            model_name='productoterritorial',
            name='presupuesto_total_pad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Presupuesto total PAD'),
        ),
        migrations.AddField(
            model_name='resultadoterritorial',
            name='cod_geografico',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código geográfico'),
        ),
        migrations.AlterField(
            model_name='productoterritorial',
            name='programacion_financiera',
            field=models.JSONField(blank=True, help_text='[DEPRECATED] Usar programaciones en ProgramacionAnualPAD', null=True),
        ),
        migrations.AlterField(
            model_name='productoterritorial',
            name='programacion_fisica',
            field=models.JSONField(blank=True, help_text='[DEPRECATED] Usar programaciones en ProgramacionAnualPAD', null=True),
        ),
        migrations.AlterField(
            model_name='resultadoterritorial',
            name='programacion_financiera',
            field=models.JSONField(blank=True, help_text='[DEPRECATED] Usar programaciones en ProgramacionAnualPAD', null=True),
        ),
        migrations.AlterField(
            model_name='resultadoterritorial',
            name='programacion_fisica',
            field=models.JSONField(blank=True, help_text='[DEPRECATED] Usar programaciones en ProgramacionAnualPAD', null=True),
        ),
        migrations.CreateModel(
            name='ProgramacionAnualPAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('fisica', 'Física'), ('financiera', 'Financiera')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='pad.productoterritorial')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='pad.resultadoterritorial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programación anual PAD',
                'verbose_name_plural': 'Programaciones anuales PAD',
                'ordering': ['anio', 'tipo'],
                'unique_together': {('resultado', 'producto', 'anio', 'tipo')},
            },
        ),
    ]
