# Generated by Django 6.0.7 on 2026-07-16 20:33

from django.db import migrations


def migrar_programaciones_forward(apps, schema_editor):
    """Migra datos de JSONFields a la tabla ProgramacionAnualPAD"""
    ProgramacionAnualPAD = apps.get_model('pad', 'ProgramacionAnualPAD')
    ResultadoTerritorial = apps.get_model('pad', 'ResultadoTerritorial')
    ProductoTerritorial = apps.get_model('pad', 'ProductoTerritorial')
    total = 0

    # Migrar ResultadoTerritorial
    for rt in ResultadoTerritorial.objects.all():
        for campo, tipo in [('programacion_fisica', 'fisica'),
                            ('programacion_financiera', 'financiera')]:
            valor_dict = getattr(rt, campo, None) or {}
            if not isinstance(valor_dict, dict):
                continue
            for anio, valor in valor_dict.items():
                ProgramacionAnualPAD.objects.create(
                    resultado=rt, anio=int(anio), tipo=tipo, valor=valor
                )
                total += 1

    # Migrar ProductoTerritorial
    for pt in ProductoTerritorial.objects.all():
        for campo, tipo in [('programacion_fisica', 'fisica'),
                            ('programacion_financiera', 'financiera')]:
            valor_dict = getattr(pt, campo, None) or {}
            if not isinstance(valor_dict, dict):
                continue
            for anio, valor in valor_dict.items():
                ProgramacionAnualPAD.objects.create(
                    producto=pt, anio=int(anio), tipo=tipo, valor=valor
                )
                total += 1


def migrar_programaciones_reverse(apps, schema_editor):
    """Elimina todos los registros de ProgramacionAnualPAD"""
    ProgramacionAnualPAD = apps.get_model('pad', 'ProgramacionAnualPAD')
    ProgramacionAnualPAD.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0003_productoterritorial_cuenta_con_financiamiento_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrar_programaciones_forward,
            migrar_programaciones_reverse,
        ),
    ]
