# Generated by Django 6.0.7 on 2026-08-17 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0005_gestion_fk_gestionfiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacionanualpad',
            options={'ordering': ['gestion__anio', 'tipo'], 'verbose_name': 'Programación anual PAD', 'verbose_name_plural': 'Programaciones anuales PAD'},
        ),
    ]
