# Generated by Django 6.0.7 on 2026-08-09 17:24
# Seed IAM (WP-03 / ADR-003): catalogo de capacidades + mapeo por rol.
# Idempotente: get_or_create; preserva mapeos manuales posteriores.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CAPACIDADES = [
    # SIS-PE
    ('sis_pe.instrumento.read', 'Leer instrumentos', 'sis-pe'),
    ('sis_pe.instrumento.create', 'Crear instrumentos', 'sis-pe'),
    ('sis_pe.pad.edit', 'Editar PAD', 'sis-pe'),
    ('sis_pe.pad.validate', 'Validar PAD', 'sis-pe'),
    ('sis_pe.pei.edit', 'Editar PEI', 'sis-pe'),
    ('sis_pe.articulacion.manage', 'Gestionar articulacion', 'sis-pe'),
    ('sis_pe.indicadores.read', 'Leer indicadores', 'sis-pe'),
    ('sis_pe.indicadores.measure', 'Registrar mediciones', 'sis-pe'),
    ('sis_pe.approve', 'Aprobar estrategico', 'sis-pe'),
    # SIS-POA
    ('sis_poa.formulate', 'Formular POA/POAU', 'sis-poa'),
    ('sis_poa.poau.edit', 'Editar POAU', 'sis-poa'),
    ('sis_poa.budget.manage', 'Gestionar presupuesto', 'sis-poa'),
    ('sis_poa.budget.validate', 'Validar presupuesto', 'sis-poa'),
    ('sis_poa.seguimiento.manage', 'Gestionar seguimiento', 'sis-poa'),
    ('sis_poa.approve', 'Aprobar operativo', 'sis-poa'),
    # SIS-PRO
    ('sis_pro.project.read', 'Leer proyectos', 'sis-pro'),
    ('sis_pro.project.create', 'Crear proyectos', 'sis-pro'),
    ('sis_pro.preinvestment.validate', 'Validar preinversion', 'sis-pro'),
    # Plataforma
    ('platform.users.manage', 'Gestionar usuarios', 'platform'),
    ('platform.organizacion.manage', 'Gestionar organizacion', 'platform'),
    ('platform.catalogs.manage', 'Gestionar catalogos', 'platform'),
    ('platform.documentos.manage', 'Gestionar documentos', 'platform'),
    ('platform.workflow.manage', 'Gestionar workflow', 'platform'),
    ('platform.notificaciones.manage', 'Gestionar notificaciones', 'platform'),
    ('platform.reportes.read', 'Leer reportes', 'platform'),
    ('platform.audit.read', 'Leer auditoria', 'platform'),
]

# Mapeo de los roles estandar del GAMS a sus capacidades (equivalente a la
# autorizacion V1 que reemplazan).
ROL_CAPACIDADES = {
    'superadmin': [c[0] for c in CAPACIDADES],
    'admin_poa': [
        'sis_pe.instrumento.read', 'sis_pe.instrumento.create',
        'sis_pe.pad.edit', 'sis_pe.pei.edit', 'sis_pe.articulacion.manage',
        'sis_poa.formulate', 'sis_poa.poau.edit',
        'sis_poa.seguimiento.manage', 'sis_poa.approve',
        'platform.documentos.manage', 'platform.notificaciones.manage',
        'platform.reportes.read',
    ],
    'admin_presupuesto': [
        'sis_pe.instrumento.read', 'sis_poa.formulate',
        'sis_poa.budget.manage', 'sis_poa.budget.validate',
        'platform.catalogs.manage', 'platform.reportes.read',
    ],
    'responsable_unidad': [
        'sis_pe.instrumento.read', 'sis_pe.indicadores.read',
        'sis_poa.formulate', 'sis_poa.poau.edit',
        'platform.notificaciones.manage',
    ],
    'revisor_planificacion': [
        'sis_pe.instrumento.read', 'sis_pe.pad.validate',
        'sis_pe.indicadores.read', 'sis_pe.approve',
    ],
    'revisor_presupuesto': [
        'sis_poa.budget.validate', 'sis_poa.approve',
        'platform.reportes.read',
    ],
    'revisor_inversion': [
        'sis_pro.project.read', 'sis_pro.preinvestment.validate',
    ],
    'revisor_juridico': [
        'sis_pro.project.read', 'platform.documentos.manage',
    ],
    'mae': [
        'sis_pe.instrumento.read', 'sis_pe.indicadores.read',
        'sis_pe.approve', 'sis_poa.approve', 'sis_pro.project.read',
        'platform.reportes.read',
    ],
    'auditor': [
        'platform.audit.read', 'platform.reportes.read',
        'sis_pe.instrumento.read',
    ],
    'consulta': [
        'sis_pe.instrumento.read', 'sis_pe.indicadores.read',
        'platform.reportes.read',
    ],
    'control_social': [
        'sis_pe.instrumento.read', 'sis_pe.indicadores.read',
    ],
}


def seed_capacidades(apps, schema_editor):
    Capacidad = apps.get_model('accounts', 'Capacidad')
    Rol = apps.get_model('accounts', 'Rol')

    por_codigo = {}
    for orden, (codigo, nombre, sistema) in enumerate(CAPACIDADES):
        cap, _ = Capacidad.objects.get_or_create(
            codigo=codigo,
            defaults={'nombre': nombre, 'sistema': sistema, 'orden': orden},
        )
        por_codigo[codigo] = cap

    # Roles estandar (si no existen aun, p.ej. instalacion sin seed previo)
    roles_estandar = {
        'superadmin': 'Superadministrador Tecnico',
        'admin_poa': 'Administrador POA',
        'admin_presupuesto': 'Administrador de Presupuesto',
        'responsable_unidad': 'Responsable POA de Unidad',
        'revisor_planificacion': 'Revisor de Planificacion',
        'revisor_presupuesto': 'Revisor de Presupuesto',
        'revisor_inversion': 'Revisor de Inversion',
        'revisor_juridico': 'Revisor Juridico',
        'mae': 'Maxima Autoridad Ejecutiva',
        'auditor': 'Auditor',
        'consulta': 'Consulta',
        'control_social': 'Control Social',
    }
    for codigo, nombre in roles_estandar.items():
        Rol.objects.get_or_create(
            codigo=codigo,
            defaults={
                'nombre': nombre,
                'es_sistema': True,
            },
        )

    for rol_codigo, cap_codigos in ROL_CAPACIDADES.items():
        rol = Rol.objects.filter(codigo=rol_codigo).first()
        if not rol:
            continue
        actuales = set(rol.capacidades.values_list('codigo', flat=True))
        nuevas = [por_codigo[c] for c in cap_codigos if c not in actuales]
        if nuevas:
            rol.capacidades.add(*nuevas)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('sistema', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capacidad',
                'verbose_name_plural': 'Capacidades',
                'ordering': ['sistema', 'orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AlcanceOrganizacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances_usuarios', to='organizacion.unidadorganizacional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcances_organizacionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alcance organizacional',
                'verbose_name_plural': 'Alcances organizacionales',
                'ordering': ['usuario', 'unidad'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='capacidades',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.capacidad'),
        ),
        migrations.RunPython(seed_capacidades, migrations.RunPython.noop),
    ]
