# Generated by Django 6.0.7 on 2026-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sis_poa_budget_audit_read'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='capacidades',
            field=models.ManyToManyField(blank=True, db_table='cuentas_rol_capacidades', related_name='roles', to='accounts.capacidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='cuentas_usuario_grupos', help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='cuentas_usuario_roles', related_name='usuarios', to='accounts.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='cuentas_usuario_permisos', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='alcanceorganizacional',
            table='cuentas_alcance_organizacional',
        ),
        migrations.AlterModelTable(
            name='capacidad',
            table='cuentas_capacidad',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='cuentas_rol',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='cuentas_usuario',
        ),
    ]
