# Generated by Django 6.0.7 on 2026-08-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_roles_poa_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcanceorganizacional',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alcanceorganizacional',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alcances', to='accounts.rol'),
        ),
        migrations.AddField(
            model_name='alcanceorganizacional',
            name='scope_type',
            field=models.CharField(choices=[('SELF', 'Self'), ('DESCENDANTS', 'Descendants'), ('GLOBAL', 'Global')], default='SELF', max_length=12),
        ),
    ]
