# Generated by F1.5 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alcanceorganizacional_scope_rol_fiscal_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
