# Generated by F1.5 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rol_deprecated'),
        ('gestion', '0004_gestionfiscal_fiscal_year_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcanceorganizacional',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='alcanceorganizacional',
            name='fiscal_year',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alcances_organizacionales',
                to='gestion.gestionfiscal',
            ),
        ),
    ]
