# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaPresupuestariaLegal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('limite', 'Límite'), ('minimo', 'Mínimo'), ('advertencia', 'Advertencia'), ('prohibicion', 'Prohibición'), ('consistencia', 'Consistencia'), ('documentacion', 'Documentación')], max_length=20)),
                ('severidad', models.CharField(choices=[('informativa', 'Informativa'), ('advertencia', 'Advertencia'), ('bloqueante', 'Bloqueante')], default='bloqueante', max_length=20)),
                ('formula', models.TextField(blank=True, help_text='Expresión segura para evaluación (implementada como método, no eval)')),
                ('parametros', models.JSONField(blank=True, help_text='Parámetros versionados en JSON: {"porcentaje": 0.10, "fuentes_permitidas": [...]}', null=True)),
                ('condicion_aplicabilidad', models.TextField(blank=True, help_text='Descripción de cuándo se aplica esta regla')),
                ('gestion_desde', models.PositiveIntegerField()),
                ('gestion_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente_normativa', models.CharField(blank=True, max_length=500)),
                ('mensaje', models.TextField(help_text='Mensaje comprensible para el usuario cuando la regla se incumple')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla presupuestaria legal',
                'verbose_name_plural': 'Reglas presupuestarias legales',
                'ordering': ['gestion_desde', 'orden'],
                'indexes': [models.Index(fields=['tipo', 'severidad'], name='normativa_r_tipo_831052_idx')],
            },
        ),
        migrations.CreateModel(
            name='VersionNormativa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('ley', 'Ley'), ('decreto', 'Decreto Supremo'), ('resolucion', 'Resolución Ministerial'), ('directriz', 'Directriz de Formulación'), ('norma', 'Norma Básica'), ('ordenanza', 'Ordenanza Municipal'), ('otro', 'Otro')], max_length=50)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('gestion', models.PositiveIntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='normativa/')),
                ('resumen', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión normativa',
                'verbose_name_plural': 'Versiones normativas',
                'ordering': ['-gestion', '-fecha_emision'],
                'indexes': [models.Index(fields=['gestion', 'tipo'], name='normativa_v_gestion_ed12cb_idx')],
            },
        ),
    ]
