# Generated by Django 6.0.7 on 2026-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglapresupuestarialegal',
            name='tipo',
            field=models.CharField(choices=[('limite', 'Límite'), ('minimo', 'Mínimo'), ('advertencia', 'Advertencia'), ('prohibicion', 'Prohibición'), ('consistencia', 'Consistencia'), ('documentacion', 'Documentación'), ('porcentaje', 'Porcentaje'), ('imputacion', 'Imputación'), ('programa', 'Programa'), ('fuente', 'Fuente'), ('personal', 'Personal'), ('destino', 'Destino'), ('codigo', 'Código')], max_length=20),
        ),
    ]
