# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimacionRecurso',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('memoria_calculo', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='catalogos.organismofinanciador')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimaciones', to='catalogos.rubrorecurso')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estimación de recurso',
                'verbose_name_plural': 'Estimaciones de recursos',
                'ordering': ['gestion', 'rubro__codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstimacionPlurianual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveIntegerField()),
                ('monto_proyectado', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estimacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='recursos.estimacionrecurso')),
            ],
            options={
                'verbose_name': 'Estimación plurianual',
                'verbose_name_plural': 'Estimaciones plurianuales',
                'ordering': ['estimacion_origen', 'anio'],
            },
        ),
        migrations.AddIndex(
            model_name='estimacionrecurso',
            index=models.Index(fields=['gestion', 'fuente'], name='recursos_es_gestion_100fa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimacionplurianual',
            unique_together={('estimacion_origen', 'anio')},
        ),
    ]
