# Generated by Django 6.0.7 on 2026-08-19 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territorio', '0002_alter_localizacionterritorial_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaPriorizacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField(db_index=True, verbose_name='Gestión POA')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de acta')),
                ('otb', models.CharField(max_length=300, verbose_name='OTB / Junta vecinal')),
                ('presidente', models.CharField(max_length=200, verbose_name='Presidente')),
                ('responsable_registro', models.CharField(blank=True, max_length=200, verbose_name='Responsable del registro')),
                ('fecha', models.DateField(verbose_name='Fecha de la priorización')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_priorizacion', to='territorio.distrito', verbose_name='Distrito')),
                ('unidad_territorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_priorizacion', to='territorio.unidadterritorial', verbose_name='Unidad territorial')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acta de priorización',
                'verbose_name_plural': 'Actas de priorización',
                'ordering': ['distrito__codigo', 'otb'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoCatalogo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Nombre del proyecto')),
                ('nombre_busqueda', models.TextField(db_index=True, verbose_name='Nombre normalizado')),
                ('sisin', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Código SISIN')),
                ('categoria_programatica', models.CharField(blank=True, max_length=60, verbose_name='Categoría programática')),
                ('denominacion_categoria', models.TextField(blank=True, verbose_name='Denominación de la categoría')),
                ('origen', models.CharField(choices=[('SIGEP', 'Reporte SIGEP'), ('HISTORICO', 'Acta de gestiones anteriores'), ('MANUAL', 'Cargado a mano')], default='MANUAL', max_length=12, verbose_name='Origen')),
                ('veces_priorizado', models.PositiveIntegerField(default=0, verbose_name='Veces priorizado')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto del catálogo',
                'verbose_name_plural': 'Proyectos del catálogo',
                'ordering': ['-veces_priorizado', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoPriorizado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('nombre', models.TextField(verbose_name='Nombre del proyecto')),
                ('sisin', models.CharField(blank=True, max_length=30, verbose_name='Código SISIN')),
                ('categoria_programatica', models.CharField(blank=True, max_length=60, verbose_name='Categoría programática')),
                ('denominacion_categoria', models.TextField(blank=True, verbose_name='Denominación de la categoría')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monto Bs.')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='priorizacion.actapriorizacion', verbose_name='Acta')),
                ('catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priorizaciones', to='priorizacion.proyectocatalogo', verbose_name='Proyecto del catálogo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto priorizado',
                'verbose_name_plural': 'Proyectos priorizados',
                'ordering': ['acta', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='actapriorizacion',
            constraint=models.UniqueConstraint(fields=('gestion', 'distrito', 'otb'), name='acta_unica_por_otb_y_gestion'),
        ),
        migrations.AddConstraint(
            model_name='proyectocatalogo',
            constraint=models.UniqueConstraint(fields=('nombre_busqueda', 'sisin'), name='proyecto_catalogo_unico'),
        ),
    ]
