# Generated by Django 6.0.7 on 2026-08-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actapriorizacion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la priorización'),
        ),
    ]
