# Generated by Django 6.0.7 on 2026-08-19 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorizacion', '0002_fecha_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaActa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de la plantilla')),
                ('gestion', models.PositiveIntegerField(blank=True, help_text='Vacío: sirve para cualquier gestión.', null=True, verbose_name='Gestión')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('encabezado', models.TextField(verbose_name='Párrafo de encabezado')),
                ('rotulo_descripcion', models.CharField(default='DESCRIPCION', max_length=80, verbose_name='Rótulo de la columna')),
                ('rotulo_monto', models.CharField(default='MONTO BS.-', max_length=80, verbose_name='Rótulo del monto')),
                ('rotulo_total', models.CharField(default='TOTAL', max_length=80, verbose_name='Rótulo del total')),
                ('nota', models.TextField(blank=True, verbose_name='Nota al pie')),
                ('cierre', models.TextField(blank=True, verbose_name='Párrafo de cierre')),
                ('firmas', models.JSONField(blank=True, default=list, help_text='Lista de {"rol": "...", "campo": "presidente|responsable"}.', verbose_name='Firmas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de acta',
                'verbose_name_plural': 'Plantillas de acta',
                'ordering': ['-gestion', 'nombre'],
            },
        ),
    ]
