# Generated by Django 6.0.7 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorizacion', '0003_plantilla_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaacta',
            name='aclaracion',
            field=models.TextField(blank=True, help_text='Párrafo que va debajo de la tabla de proyectos.', verbose_name='Aclaración sobre los recursos'),
        ),
    ]
