# Generated by Django 6.0.7 on 2026-08-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_clasificadorinstitucional_version_clasificador_and_more'),
        ('priorizacion', '0004_aclaracion_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectopriorizado',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_priorizados', to='catalogos.fuentefinanciamiento', verbose_name='Fuente de financiamiento'),
        ),
        migrations.AddField(
            model_name='proyectopriorizado',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_priorizados', to='catalogos.organismofinanciador', verbose_name='Organismo financiador'),
        ),
    ]
