# Generated by Django 6.0.7 on 2026-08-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_revision_por_categoria_programatica'),
        ('priorizacion', '0005_financiamiento_priorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectopriorizado',
            name='apertura_fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priorizaciones', to='budget.aperturafuente', verbose_name='Fila de gasto donde se cargó'),
        ),
        migrations.AddField(
            model_name='proyectopriorizado',
            name='monto_materializado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monto ya volcado al gasto'),
        ),
    ]
