# Generated by Django 6.0.7 on 2026-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priorizacion', '0006_rastro_materializacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actapriorizacion',
            name='es_pavimento',
            field=models.BooleanField(default=False, verbose_name='Proyecto de pavimentación'),
        ),
    ]
