# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidad', models.CharField(help_text='Nombre del modelo asociado', max_length=50)),
                ('entidad_id', models.CharField(help_text='ID del registro', max_length=100)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tipo_documento', models.CharField(blank=True, max_length=100)),
                ('hash_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('tamanio_bytes', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('gestion', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento adjunto',
                'verbose_name_plural': 'Documentos adjuntos',
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='documentos__entidad_35f03c_idx'), models.Index(fields=['gestion'], name='documentos__gestion_b8d22a_idx')],
            },
        ),
    ]
