# Generated by Django 6.0.7 on 2026-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documentoadjunto_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadjunto',
            name='contenido_cifrado',
            field=models.BinaryField(blank=True, null=True, verbose_name='Contenido cifrado'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='content_type',
            field=models.CharField(blank=True, default='application/pdf', max_length=120, verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='nonce',
            field=models.BinaryField(blank=True, null=True, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='documentoadjunto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
