# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechoPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='techos', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='techos', to='catalogos.organismofinanciador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Techo presupuestario',
                'verbose_name_plural': 'Techos presupuestarios',
                'ordering': ['-gestion', 'fuente__codigo'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionTecho',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_techo', to='organizacion.direccionadministrativa')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_techo', to='presupuesto.programapresupuestario')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_techo', to='organizacion.unidadejecutora')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_techo', to='organizacion.unidadorganizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('techo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='techos.techopresupuestario')),
            ],
            options={
                'verbose_name': 'Distribución de techo',
                'verbose_name_plural': 'Distribuciones de techo',
                'ordering': ['techo', 'da', 'ue'],
            },
        ),
        migrations.AddIndex(
            model_name='techopresupuestario',
            index=models.Index(fields=['gestion', 'fuente', 'organismo'], name='techos_tech_gestion_e2661f_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['techo', 'unidad'], name='techos_dist_techo_i_439cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['techo', 'programa'], name='techos_dist_techo_i_741a7e_idx'),
        ),
    ]
