# Generated by Django 6.0.7 on 2026-07-20 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTecho',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('asignacion', 'Asignación'), ('incremento', 'Incremento'), ('reduccion', 'Reducción'), ('transferencia', 'Transferencia'), ('reserva', 'Reserva'), ('liberacion', 'Liberación'), ('ajuste', 'Ajuste'), ('reversion', 'Reversión')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('justification', models.TextField()),
                ('document', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_techo_aprobados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_ceiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='techos.techopresupuestario')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_techo_solicitados', to=settings.AUTH_USER_MODEL)),
                ('source_ceiling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='techos.techopresupuestario')),
                ('techo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='techos.techopresupuestario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de techo',
                'verbose_name_plural': 'Movimientos de techo',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['techo', 'movement_type'], name='techos_movi_techo_i_ee85d8_idx'), models.Index(fields=['date'], name='techos_movi_date_5e4a53_idx')],
            },
        ),
    ]
