# Generated by Django 6.0.7 on 2026-08-11 14:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('organizacion', '0001_initial'),
        ('presupuesto', '0004_blindaje_categoria_programatica'),
        ('techos', '0002_movimientotecho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='techopresupuestario',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='GastoObligatorio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=300)),
                ('base_legal', models.CharField(blank=True, default='', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='organizacion.direccionadministrativa')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='catalogos.fuentefinanciamiento')),
                ('objeto_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='catalogos.objetogasto')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='catalogos.organismofinanciador')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='presupuesto.programapresupuestario')),
                ('techo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_obligatorios', to='techos.techopresupuestario')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='organizacion.unidadejecutora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto obligatorio',
                'verbose_name_plural': 'Gastos obligatorios',
                'ordering': ['techo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RecursoTecho',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rubro', models.CharField(blank=True, default='', max_length=20)),
                ('rubro_descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('entidad_otorgante', models.CharField(blank=True, default='', max_length=200)),
                ('concepto', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.organismofinanciador')),
                ('techo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='techos.techopresupuestario')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso del techo',
                'verbose_name_plural': 'Recursos del techo',
                'ordering': ['techo', 'orden'],
            },
        ),
    ]
