# Generated by Django 6.0.7 on 2026-08-11 22:44

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # atomic=False: los AlterField a NUMERIC(18,2) sobre tablas con datos
    # reescriben la tabla; en PostgreSQL las FKs del proyecto son
    # DEFERRABLE INITIALLY DEFERRED y la reescritura encola eventos de
    # trigger diferidos que bloquean el siguiente ALTER en la misma
    # transacción ("cannot ALTER TABLE ... pending trigger events", PG15+).
    # Con atomic=False cada sentencia DDL commitea y los eventos resuelven
    # antes del siguiente ALTER. La data-migration 0004_nucleo_techo_datos
    # conserva su propio transaction.atomic() (design §5).
    atomic = False

    dependencies = [
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('gestion', '0002_alter_gestionfiscal_estado_and_more'),
        ('organizacion', '0001_initial'),
        ('presupuesto', '0004_blindaje_categoria_programatica'),
        ('techos', '0003_techopresupuestario_concepto_gastoobligatorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustePresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INCREMENTO', 'Incremento'), ('REDUCCION', 'Reducción'), ('RECLASIFICACION', 'Reclasificación')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('motivo', models.TextField(blank=True, default='')),
                ('documento', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ajuste presupuestario',
                'verbose_name_plural': 'Ajustes presupuestarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BolsaPresupuestaria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_gasto', models.CharField(choices=[('CORRIENTE', 'Corriente'), ('INVERSION', 'Inversión')], default='CORRIENTE', max_length=10)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_ajustes', models.DecimalField(decimal_places=2, default=0, help_text='Puede ser negativo (REDUCCION); solo lo escribe el servicio', max_digits=18)),
                ('monto_vigente', models.DecimalField(decimal_places=2, help_text='= monto_inicial + monto_ajustes (C8); solo lo escribe el servicio', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_reservado', models.DecimalField(decimal_places=2, default=0, help_text='Solo lo escribe el servicio bajo lock', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Bolsa presupuestaria',
                'verbose_name_plural': 'Bolsas presupuestarias',
                'ordering': ['techo', 'fuente__codigo', 'organismo__codigo', 'tipo_gasto'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPresupuestario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DISTRIBUCION', 'Distribución'), ('RESERVA', 'Reserva'), ('LIBERACION', 'Liberación'), ('REDISTRIBUCION', 'Redistribución'), ('REVERSION', 'Reversión'), ('INCREMENTO', 'Incremento'), ('REDUCCION', 'Reducción'), ('AJUSTE', 'Ajuste')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_antes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_despues', models.DecimalField(decimal_places=2, max_digits=18)),
                ('justificacion', models.TextField()),
                ('documento', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateTimeField()),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Movimiento presupuestario',
                'verbose_name_plural': 'Movimientos presupuestarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TechoRecursoDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rubro', models.CharField(blank=True, default='', max_length=20)),
                ('concepto', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Detalle de recurso del techo',
                'verbose_name_plural': 'Detalles de recursos del techo',
                'ordering': ['grupo', 'rubro'],
            },
        ),
        migrations.CreateModel(
            name='TechoRecursoGrupo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_inversion', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Grupo de recursos del techo',
                'verbose_name_plural': 'Grupos de recursos del techo',
                'ordering': ['techo', 'fuente__codigo', 'organismo__codigo'],
            },
        ),
        migrations.AddField(
            model_name='distribuciontecho',
            name='categoria_programatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_techo', to='presupuesto.categoriaprogramatica'),
        ),
        migrations.AddField(
            model_name='distribuciontecho',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='techos.distribuciontecho'),
        ),
        migrations.AddField(
            model_name='gastoobligatorio',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='presupuesto.actividadpresupuestaria'),
        ),
        migrations.AddField(
            model_name='gastoobligatorio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios_techo', to='presupuesto.proyectopresupuestario'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='presupuesto.actividadpresupuestaria'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='organizacion.direccionadministrativa'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='objeto_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.objetogasto'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='presupuesto.programapresupuestario'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='presupuesto.proyectopresupuestario'),
        ),
        migrations.AddField(
            model_name='recursotecho',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='organizacion.unidadejecutora'),
        ),
        migrations.AddField(
            model_name='techopresupuestario',
            name='gestion_fiscal',
            # Desviación deliberada del estado final: FK nullable SIN unique
            # para permitir el pre-check C2 de la data-migration
            # (0004_nucleo_techo_datos) antes de imponer 1:1. La migración
            # de datos hace el backfill y el AlterField final a
            # OneToOneField no-null + unique.
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='techo', to='gestion.gestionfiscal', verbose_name='Gestión fiscal'),
        ),
        migrations.AddField(
            model_name='techopresupuestario',
            name='otras_afectaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Afectaciones adicionales al techo (gap §12.3 del design)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='distribuciontecho',
            name='monto_asignado',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='distribuciontecho',
            name='monto_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gastoobligatorio',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recursotecho',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='techopresupuestario',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='gastoobligatorio',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_gasto_obligatorio_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='recursotecho',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_recurso_techo_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='techopresupuestario',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gte', 0)), name='ck_techo_monto_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='techopresupuestario',
            constraint=models.CheckConstraint(condition=models.Q(('otras_afectaciones__gte', 0)), name='ck_techo_otras_afectaciones_no_negativo'),
        ),
        migrations.AddField(
            model_name='ajustepresupuestario',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustepresupuestario',
            name='techo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='techos.techopresupuestario'),
        ),
        migrations.AddField(
            model_name='ajustepresupuestario',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustepresupuestario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_presupuestarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsapresupuestaria',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsapresupuestaria',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_techo', to='catalogos.fuentefinanciamiento'),
        ),
        migrations.AddField(
            model_name='bolsapresupuestaria',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_techo', to='catalogos.organismofinanciador'),
        ),
        migrations.AddField(
            model_name='bolsapresupuestaria',
            name='techo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsas', to='techos.techopresupuestario'),
        ),
        migrations.AddField(
            model_name='bolsapresupuestaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustepresupuestario',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='techos.bolsapresupuestaria'),
        ),
        migrations.AddField(
            model_name='distribuciontecho',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='techos.bolsapresupuestaria'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['techo'], name='techos_dist_techo_i_20a7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['padre'], name='techos_dist_padre_i_85d8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['bolsa'], name='techos_dist_bolsa_i_dab1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['categoria_programatica'], name='techos_dist_categor_c2e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='distribuciontecho',
            index=models.Index(fields=['unidad'], name='techos_dist_unidad__9364c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='distribuciontecho',
            constraint=models.CheckConstraint(condition=models.Q(('monto_asignado__gte', 0)), name='ck_distribucion_asignado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='distribuciontecho',
            constraint=models.CheckConstraint(condition=models.Q(('monto_reserva__gte', 0)), name='ck_distribucion_reserva_no_negativo'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_presupuestarios', to='techos.bolsapresupuestaria'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='distribucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_presupuestarios', to='techos.distribuciontecho'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguiente', to='techos.movimientopresupuestario'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='reversa_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversiones', to='techos.movimientopresupuestario'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='techo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_presupuestarios', to='techos.techopresupuestario'),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientopresupuestario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_presupuestarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techorecursodetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techorecursodetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techorecursogrupo',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techorecursogrupo',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_recursos_techo', to='catalogos.fuentefinanciamiento'),
        ),
        migrations.AddField(
            model_name='techorecursogrupo',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_recursos_techo', to='catalogos.organismofinanciador'),
        ),
        migrations.AddField(
            model_name='techorecursogrupo',
            name='techo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_recursos', to='techos.techopresupuestario'),
        ),
        migrations.AddField(
            model_name='techorecursogrupo',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techorecursodetalle',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='techos.techorecursogrupo'),
        ),
        migrations.AddIndex(
            model_name='bolsapresupuestaria',
            index=models.Index(fields=['techo'], name='techos_bols_techo_i_e288cf_idx'),
        ),
        migrations.AddIndex(
            model_name='bolsapresupuestaria',
            index=models.Index(fields=['fuente'], name='techos_bols_fuente__b905d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bolsapresupuestaria',
            index=models.Index(fields=['organismo'], name='techos_bols_organis_6ba686_idx'),
        ),
        migrations.AddIndex(
            model_name='bolsapresupuestaria',
            index=models.Index(fields=['tipo_gasto'], name='techos_bols_tipo_ga_796249_idx'),
        ),
        migrations.AddConstraint(
            model_name='bolsapresupuestaria',
            constraint=models.UniqueConstraint(fields=('techo', 'fuente', 'organismo', 'tipo_gasto'), name='uniq_bolsa_techo_fuente_organismo_tipo_gasto', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bolsapresupuestaria',
            constraint=models.CheckConstraint(condition=models.Q(('monto_inicial__gte', 0)), name='ck_bolsa_inicial_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='bolsapresupuestaria',
            constraint=models.CheckConstraint(condition=models.Q(('monto_vigente__gte', 0)), name='ck_bolsa_vigente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='bolsapresupuestaria',
            constraint=models.CheckConstraint(condition=models.Q(('monto_reservado__gte', 0)), name='ck_bolsa_reservado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='bolsapresupuestaria',
            constraint=models.CheckConstraint(condition=models.Q(('monto_vigente', django.db.models.expressions.CombinedExpression(models.F('monto_inicial'), '+', models.F('monto_ajustes')))), name='ck_bolsa_vigente_igual_inicial_mas_ajustes'),
        ),
        migrations.AddIndex(
            model_name='ajustepresupuestario',
            index=models.Index(fields=['techo'], name='techos_ajus_techo_i_cf38dc_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustepresupuestario',
            index=models.Index(fields=['bolsa'], name='techos_ajus_bolsa_i_55b6ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='ajustepresupuestario',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_ajuste_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='movimientopresupuestario',
            index=models.Index(fields=['techo', 'tipo'], name='techos_movi_techo_i_9e8a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientopresupuestario',
            index=models.Index(fields=['fecha'], name='techos_movi_fecha_2da321_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientopresupuestario',
            index=models.Index(fields=['bolsa'], name='techos_movi_bolsa_i_9acca3_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientopresupuestario',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_movimiento_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='techorecursogrupo',
            index=models.Index(fields=['techo'], name='techos_tech_techo_i_a0a6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='techorecursogrupo',
            index=models.Index(fields=['fuente'], name='techos_tech_fuente__6fdf6d_idx'),
        ),
        migrations.AddIndex(
            model_name='techorecursogrupo',
            index=models.Index(fields=['organismo'], name='techos_tech_organis_6c1e9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='techorecursogrupo',
            constraint=models.UniqueConstraint(fields=('techo', 'fuente', 'organismo'), name='uniq_grupo_recursos_techo_fuente_organismo', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='techorecursogrupo',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_grupo_recursos_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='techorecursogrupo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_corriente__gte', 0)), name='ck_grupo_recursos_corriente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='techorecursogrupo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_inversion__gte', 0)), name='ck_grupo_recursos_inversion_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='techorecursodetalle',
            index=models.Index(fields=['grupo'], name='techos_tech_grupo_i_b1fb73_idx'),
        ),
        migrations.AddConstraint(
            model_name='techorecursodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_detalle_recursos_monto_no_negativo'),
        ),
    ]
