# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['accion_corto_plazo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(choices=[('terminal', 'Terminal'), ('intermedio', 'Intermedio')], default='terminal', max_length=20)),
                ('estado', models.CharField(choices=[('acabado', 'Acabado'), ('proceso', 'En proceso')], default='acabado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Supuesto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('riesgo_externo', models.TextField(blank=True)),
                ('probabilidad', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Supuesto',
                'verbose_name_plural': 'Supuestos',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('formula', models.TextField(blank=True, help_text='Fórmula del indicador')),
                ('tipo_comportamiento', models.CharField(choices=[('acumulable', 'Acumulable'), ('no_acumulable', 'No Acumulable'), ('promedio', 'Promedio'), ('hito', 'Hito'), ('porcentaje', 'Porcentaje'), ('cualitativo', 'Cualitativo')], default='acumulable', max_length=20)),
                ('linea_base', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('anio_linea_base', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente_linea_base', models.CharField(blank=True, max_length=500)),
                ('meta_anual', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('medio_verificacion', models.TextField(blank=True)),
                ('frecuencia_medicion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to=settings.AUTH_USER_MODEL)),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='catalogos.unidadmedida')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MedioVerificacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('soporte_esperado', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_verificacion', to='indicadores.indicador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medio de verificación',
                'verbose_name_plural': 'Medios de verificación',
            },
        ),
        migrations.CreateModel(
            name='MetaProgramada',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField()),
                ('meta_anual', models.DecimalField(decimal_places=4, max_digits=20)),
                ('trimestre1', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('trimestre2', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('trimestre3', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('trimestre4', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_programadas', to='indicadores.indicador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta programada',
                'verbose_name_plural': 'Metas programadas',
                'ordering': ['indicador', 'gestion', '-version'],
            },
        ),
    ]
