# Generated by Django 6.0.7 on 2026-07-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('indicadores', '0001_initial'),
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='accion_corto_plazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='planificacion.accioncortoplazo'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='catalogos.tipooperacion'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='accion_corto_plazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='planificacion.accioncortoplazo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogos.tipoproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supuesto',
            name='accion_corto_plazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supuestos', to='planificacion.accioncortoplazo'),
        ),
        migrations.AddField(
            model_name='supuesto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supuesto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='indicadores.operacion'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='metaprogramada',
            unique_together={('indicador', 'gestion', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='operacion',
            unique_together={('accion_corto_plazo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('accion_corto_plazo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together={('operacion', 'codigo')},
        ),
    ]
