# Generated by Django 6.0.7 on 2026-07-29 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0004_alter_nodoplanificacion_nivel_alter_plan_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionCatalogoPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('cerrado', 'Cerrado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('norma_aprobacion', models.CharField(blank=True, max_length=300, verbose_name='Norma de aprobación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_catalogo', to='planificacion.plan', verbose_name='Plan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de catálogo de plan',
                'verbose_name_plural': 'Versiones de catálogo de planes',
                'ordering': ['plan', 'gestion'],
                'indexes': [models.Index(fields=['estado'], name='codificacio_estado_0fca37_idx'), models.Index(fields=['gestion'], name='codificacio_gestion_c48575_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'gestion'), name='uniq_version_catalogo_plan_gestion'), models.UniqueConstraint(condition=models.Q(('estado', 'vigente')), fields=('plan',), name='uniq_version_catalogo_vigente_por_plan')],
            },
        ),
    ]
