# Generated by Django 6.0.7 on 2026-07-29 22:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjePGDESA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=500, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo')),
            ],
            options={
                'verbose_name': 'Eje PGDESA',
                'verbose_name_plural': 'Ejes PGDESA',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentePDESA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=500, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='codificacion.ejepgdesa', verbose_name='Eje PGDESA')),
            ],
            options={
                'verbose_name': 'Componente PDESA',
                'verbose_name_plural': 'Componentes PDESA',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=500, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='codificacion.componentepdesa', verbose_name='Componente PDESA')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo')),
            ],
            options={
                'verbose_name': 'Sector económico',
                'verbose_name_plural': 'Sectores económicos',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoSectorial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=500, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='codificacion.sectoreconomico', verbose_name='Sector económico')),
            ],
            options={
                'verbose_name': 'Resultado sectorial',
                'verbose_name_plural': 'Resultados sectoriales',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='ejepgdesa',
            constraint=models.UniqueConstraint(fields=('codigo', 'version_catalogo'), name='uniq_eje_pgdesa_codigo_version'),
        ),
        migrations.AddIndex(
            model_name='componentepdesa',
            index=models.Index(fields=['eje', 'activo'], name='codificacio_eje_id_b198fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentepdesa',
            constraint=models.UniqueConstraint(fields=('eje', 'codigo', 'version_catalogo'), name='uniq_componente_pdesa_padre_codigo_version'),
        ),
        migrations.AddIndex(
            model_name='sectoreconomico',
            index=models.Index(fields=['componente', 'activo'], name='codificacio_compone_b845e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectoreconomico',
            constraint=models.UniqueConstraint(fields=('componente', 'codigo', 'version_catalogo'), name='uniq_sector_padre_codigo_version'),
        ),
        migrations.AddIndex(
            model_name='resultadosectorial',
            index=models.Index(fields=['sector', 'activo'], name='codificacio_sector__bc7595_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultadosectorial',
            constraint=models.UniqueConstraint(fields=('sector', 'codigo', 'version_catalogo'), name='uniq_resultado_sectorial_padre_codigo_version'),
        ),
    ]
