# Generated by Django 6.0.7 on 2026-07-29 22:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0002_ejepgdesa_componentepdesa_sectoreconomico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadCodificadora',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El código de entidad debe tener exactamente 4 dígitos numéricos.', regex='^\\d{4}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=300, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidad codificadora',
                'verbose_name_plural': 'Entidades codificadoras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EntidadTerritorialCGEO',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='El código CGEO debe tener exactamente 6 dígitos numéricos.', regex='^\\d{6}$')], verbose_name='Código CGEO (INE)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nivel', models.CharField(choices=[('departamento', 'Departamento'), ('provincia', 'Provincia'), ('municipio', 'Municipio')], max_length=20, verbose_name='Nivel')),
                ('estado', models.CharField(choices=[('provisional', 'Provisional'), ('oficial', 'Oficial')], default='provisional', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='codificacion.entidadterritorialcgeo', verbose_name='Entidad padre')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidad territorial CGEO',
                'verbose_name_plural': 'Entidades territoriales CGEO',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineamientoPAD',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='El código debe tener exactamente 2 dígitos numéricos.', regex='^\\d{2}$')], verbose_name='Código')),
                ('denominacion', models.CharField(max_length=500, verbose_name='Denominación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineamientos_pad', to='codificacion.entidadterritorialcgeo', verbose_name='Entidad territorial CGEO')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo')),
            ],
            options={
                'verbose_name': 'Lineamiento PAD',
                'verbose_name_plural': 'Lineamientos PAD',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='entidadterritorialcgeo',
            index=models.Index(fields=['nivel', 'estado'], name='codificacio_nivel_921cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='lineamientopad',
            index=models.Index(fields=['entidad_territorial', 'activo'], name='codificacio_entidad_f006f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineamientopad',
            constraint=models.UniqueConstraint(fields=('entidad_territorial', 'codigo', 'version_catalogo'), name='uniq_lineamiento_pad_territorio_codigo_version'),
        ),
    ]
