# Generated by Django 6.0.7 on 2026-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0004_seed_cgeo_y_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadterritorialcgeo',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código CGEO (INE)'),
        ),
    ]
