# Generated by Django 6.0.7 on 2026-07-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0005_alter_entidadterritorialcgeo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentepdesa',
            name='version_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_pdesa', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo'),
        ),
        migrations.AlterField(
            model_name='ejepgdesa',
            name='version_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejes_pgdesa', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo'),
        ),
        migrations.AlterField(
            model_name='lineamientopad',
            name='version_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineamientos_pad', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo'),
        ),
        migrations.AlterField(
            model_name='resultadosectorial',
            name='version_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_sectoriales', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo'),
        ),
        migrations.AlterField(
            model_name='sectoreconomico',
            name='version_catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores_economicos', to='codificacion.versioncatalogoplan', verbose_name='Versión de catálogo'),
        ),
    ]
