# Generated by Django 6.0.7 on 2026-07-30 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0006_alter_componentepdesa_version_catalogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomologacionCodigo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(choices=[('resultado_pad', 'Resultado PAD'), ('producto_pad', 'Producto PAD'), ('resultado_pei', 'Resultado PEI'), ('producto_pei', 'Producto PEI'), ('accion_poa', 'Acción POA'), ('operacion_poau', 'Operación POAU'), ('actividad_poau', 'Actividad POAU'), ('tarea_poau', 'Tarea POAU')], max_length=30, verbose_name='Tipo de entidad')),
                ('entidad_id', models.UUIDField(verbose_name='ID de la entidad homologada')),
                ('codigo_anterior', models.CharField(max_length=100, verbose_name='Código anterior')),
                ('codigo_nuevo', models.CharField(max_length=100, verbose_name='Código nuevo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de homologación')),
                ('documento_respaldo', models.CharField(blank=True, max_length=300, verbose_name='Documento de respaldo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologaciones_codigo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Homologación de código',
                'verbose_name_plural': 'Homologaciones de códigos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo_entidad', 'codigo_anterior'], name='codificacio_tipo_en_27eefb_idx'), models.Index(fields=['entidad_id'], name='codificacio_entidad_70729d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaCodigo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('resultado_pad', 'Resultado PAD'), ('producto_pad', 'Producto PAD'), ('resultado_pei', 'Resultado PEI'), ('producto_pei', 'Producto PEI'), ('accion_poa', 'Acción POA'), ('operacion_poau', 'Operación POAU'), ('actividad_poau', 'Actividad POAU'), ('tarea_poau', 'Tarea POAU')], max_length=30, verbose_name='Nivel de articulación')),
                ('padre_id', models.UUIDField(blank=True, null=True, verbose_name='ID del registro padre')),
                ('gestion', models.PositiveIntegerField(verbose_name='Gestión')),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último correlativo emitido')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secuencias_codigo', to='codificacion.entidadcodificadora', verbose_name='Entidad codificadora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secuencia de código',
                'verbose_name_plural': 'Secuencias de códigos',
                'ordering': ['nivel', 'gestion'],
                'constraints': [models.UniqueConstraint(fields=('nivel', 'padre_id', 'gestion', 'entidad'), name='uniq_secuencia_codigo_clave', nulls_distinct=False)],
            },
        ),
    ]
