# Generated by Django 6.0.7 on 2026-08-04 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0008_homologacion_append_only_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncatalogoplan',
            name='clasificacion_fuente',
            field=models.CharField(choices=[('oficial', 'Oficial'), ('referencial', 'Referencial'), ('tecnica', 'Técnica'), ('incierta', 'Incierta')], default='incierta', max_length=20, verbose_name='Clasificación de la fuente'),
        ),
        migrations.AddField(
            model_name='versioncatalogoplan',
            name='procedencia_fuente',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Procedencia de la fuente'),
        ),
        migrations.AddConstraint(
            model_name='homologacioncodigo',
            constraint=models.UniqueConstraint(fields=('tipo_entidad', 'entidad_id', 'codigo_nuevo'), name='uniq_homologacion_entidad_codigo_nuevo'),
        ),
    ]
