# Generated by Django 6.0.7 on 2026-08-12 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0010_auditoria_migracion_sim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientopad',
            name='componente',
            field=models.ForeignKey(blank=True, help_text='Relación CONTIENE del catálogo maestro (opción A).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineamientos', to='codificacion.componentepdesa', verbose_name='Componente PDESA'),
        ),
        migrations.AlterField(
            model_name='lineamientopad',
            name='codigo',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='El código debe tener 2 o 3 dígitos numéricos.', regex='^\\d{2,3}$')], verbose_name='Código'),
        ),
        migrations.AddIndex(
            model_name='lineamientopad',
            index=models.Index(fields=['componente'], name='codificacio_compone_62bb6a_idx'),
        ),
    ]
