# Generated by Django 6.0.7 on 2026-08-16 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0010_auditoria_migracion_sim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineamientopad',
            name='uniq_lineamiento_pad_territorio_codigo_version',
        ),
        migrations.AddField(
            model_name='lineamientopad',
            name='componente',
            field=models.ForeignKey(blank=True, help_text='Componente del PDESA al que pertenece el lineamiento (cascada del wizard).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineamientos_pad', to='codificacion.componentepdesa', verbose_name='Componente PDESA'),
        ),
        migrations.AddIndex(
            model_name='lineamientopad',
            index=models.Index(fields=['componente'], name='codificacio_compone_62bb6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineamientopad',
            constraint=models.UniqueConstraint(condition=models.Q(('componente__isnull', False)), fields=('entidad_territorial', 'componente', 'codigo', 'version_catalogo'), name='uniq_lineamiento_pad_territorio_componente_codigo_version'),
        ),
    ]
