# Generated by Django 6.0.7 on 2026-08-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0011_lineamientopad_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentepdesa',
            name='objetivo_efecto',
            field=models.TextField(blank=True, default='', help_text='Texto oficial del objetivo de efecto del Componente PDESA (PDESA 2026-2030).', verbose_name='Objetivo de Efecto'),
        ),
        migrations.AddField(
            model_name='ejepgdesa',
            name='objetivo_impacto',
            field=models.TextField(blank=True, default='', help_text='Texto oficial del objetivo de impacto del Eje PGDESA (PDESA 2026-2030).', verbose_name='Objetivo de Impacto'),
        ),
    ]
