# Generated by Django 6.0.7 on 2026-08-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0011_remove_lineamientopad_uniq_lineamiento_pad_territorio_codigo_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentepdesa',
            name='objetivo_efecto',
            field=models.TextField(blank=True, help_text='Objetivo de efecto del PDES (autocompletado en la Matriz PAD).', verbose_name='Objetivo de efecto'),
        ),
        migrations.AddField(
            model_name='ejepgdesa',
            name='objetivo_impacto',
            field=models.TextField(blank=True, help_text='Objetivo de impacto del PGDES (autocompletado en la Matriz PAD).', verbose_name='Objetivo de impacto'),
        ),
    ]
