# Generated by Django 6.0.7 on 2026-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0013_alter_secuenciacodigo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioncatalogoplan',
            name='gestion',
            field=models.PositiveIntegerField(verbose_name='Gestión (año de vigencia del plan — excepción plurianual, PIP-DB-003: NO FK)'),
        ),
    ]
