# Generated by Django 6.0.7 on 2026-08-14 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('REPORTE_SIGEP', 'Reporte SIGEP'), ('NOTA_MEF', 'Nota MEF'), ('RESOLUCION', 'Resolución'), ('INFORME', 'Informe'), ('PROYECCION_RECURSOS_PROPIOS', 'Proyección de recursos propios'), ('OTRO', 'Otro')], default='OTRO', max_length=40)),
                ('nombre', models.CharField(max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='budget/')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_budget', to='gestion.gestionfiscal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de presupuesto',
                'verbose_name_plural': 'Documentos de presupuesto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectiveCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('FIJADO', 'Fijado')], default='BORRADOR', max_length=20)),
                ('version_actual', models.PositiveIntegerField(default=0, help_text='Número de la versión vigente del techo.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.OneToOneField(help_text='Gestión fiscal del techo (una por gestión).', on_delete=django.db.models.deletion.CASCADE, related_name='directive_ceiling', to='gestion.gestionfiscal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Techo directivo',
                'verbose_name_plural': 'Techos directivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectiveCeilingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('FIJADO', 'Fijado')], default='BORRADOR', max_length=20)),
                ('hash', models.CharField(blank=True, default='', help_text='SHA-256 de los datos semánticos; se llena al fijar.', max_length=64)),
                ('fecha_fijacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('inmutable', models.BooleanField(default=False)),
                ('ceiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='budget.directiveceiling')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fijado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techos_fijados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de techo directivo',
                'verbose_name_plural': 'Versiones de techo directivo',
                'ordering': ['ceiling', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CeilingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(choices=[('SIGEP', 'SIGEP'), ('MUNICIPAL', 'Recursos propios municipales'), ('SALDO', 'Saldo de caja y bancos'), ('OTRO', 'Otros')], max_length=20)),
                ('concepto', models.CharField(blank=True, default='', max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='budget.budgetdocument')),
                ('entidad_otorgante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.entidadtransferencia')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.organismofinanciador')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos_techo', to='catalogos.rubrorecurso')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='budget.directiveceilingversion')),
            ],
            options={
                'verbose_name': 'Recurso del techo',
                'verbose_name_plural': 'Recursos del techo',
                'ordering': ['version', 'origen', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='MandatoryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programa', models.CharField(blank=True, default='', max_length=20)),
                ('actividad', models.CharField(blank=True, default='', max_length=20)),
                ('denominacion', models.CharField(blank=True, default='', max_length=500)),
                ('entidad_transferencia', models.CharField(blank=True, default='', max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios', to='organizacion.direccionadministrativa')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_obligatorios', to='budget.budgetdocument')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios', to='catalogos.fuentefinanciamiento')),
                ('objeto_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios', to='catalogos.objetogasto')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios', to='catalogos.organismofinanciador')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obligatorios', to='organizacion.unidadejecutora')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_obligatorios', to='budget.directiveceilingversion')),
            ],
            options={
                'verbose_name': 'Gasto obligatorio',
                'verbose_name_plural': 'Gastos obligatorios',
                'ordering': ['version', 'programa', 'actividad', 'denominacion'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetdocument',
            index=models.Index(fields=['gestion'], name='budget_budg_gestion_282ec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='directiveceilingversion',
            constraint=models.UniqueConstraint(fields=('ceiling', 'numero'), name='uniq_techo_version_numero'),
        ),
        migrations.AddConstraint(
            model_name='ceilingresource',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_ceilingresource_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='mandatoryexpense',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_mandatoryexpense_monto_positivo'),
        ),
    ]
