# Generated by Django 6.0.7 on 2026-08-14 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammaticCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('denominacion', models.CharField(max_length=300)),
                ('nivel', models.CharField(choices=[('PROGRAMA', 'Programa'), ('SUBPROGRAMA', 'Subprograma'), ('PROYECTO', 'Proyecto'), ('ACTIVIDAD', 'Actividad')], default='PROGRAMA', max_length=20)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('origen', models.CharField(blank=True, default='', max_length=40)),
                ('normativa', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_programaticas', to='gestion.gestionfiscal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='budget.programmaticcategory')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CategorAa programAtica',
                'verbose_name_plural': 'CategorAas programAticas',
                'ordering': ['gestion', 'nivel', 'codigo'],
                'indexes': [models.Index(fields=['gestion', 'parent'], name='budget_prog_gestion_953fc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('gestion', 'codigo'), name='budget_categoria_gestion_codigo_uniq')],
            },
        ),
    ]
