# Generated by Django 6.0.7 on 2026-08-14 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_programmaticcategory'),
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        ('organizacion', '0001_initial'),
        ('territorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(help_text='Número de versión.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('FIJADO', 'Fijado')], default='BORRADOR', max_length=20)),
                ('hash', models.CharField(blank=True, default='', help_text='SHA-256 de los datos semánticos; se llena al fijar (Fase 7).', max_length=64)),
                ('fecha_fijacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('inmutable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fijado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_fijadas', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.ForeignKey(help_text='Gestión fiscal de la distribución.', on_delete=django.db.models.deletion.CASCADE, related_name='versiones_distribucion', to='gestion.gestionfiscal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de distribución',
                'verbose_name_plural': 'Versiones de distribución',
                'ordering': ['gestion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_sisin', models.CharField(blank=True, default='', help_text='Código SISIN (VARCHAR, ceros iniciales preservados).', max_length=20)),
                ('actividad_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('denominacion', models.CharField(max_length=300)),
                ('tipo_apertura', models.CharField(choices=[('DETAIL', 'Detalle')], default='DETAIL', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría programática del ciclo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='budget.programmaticcategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_presupuestarias', to='organizacion.direccionadministrativa')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_presupuestarias', to='territorio.distrito')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas_presupuestarias', to='gestion.gestionfiscal')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_presupuestarias', to='organizacion.unidadejecutora')),
                ('unidad_organizacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_presupuestarias', to='organizacion.unidadorganizacional')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Versión de distribución activa al momento de la apertura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas', to='budget.distributionversion')),
            ],
            options={
                'verbose_name': 'Apertura programática',
                'verbose_name_plural': 'Aperturas programáticas',
                'ordering': ['gestion', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('DISTRITAL', 'Distrital'), ('DISTRIBUCION', 'Distribución'), ('OTRA', 'Otra')], default='OTRA', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('LIBERADA', 'Liberada')], default='ACTIVA', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_por_fuente', to='catalogos.fuentefinanciamiento')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_presupuestarias', to='gestion.gestionfiscal')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_por_organismo', to='catalogos.organismofinanciador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='budget.distributionversion')),
            ],
            options={
                'verbose_name': 'Reserva presupuestaria',
                'verbose_name_plural': 'Reservas presupuestarias',
                'ordering': ['gestion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='budget.allocation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_sources', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_sources', to='catalogos.organismofinanciador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de apertura',
                'verbose_name_plural': 'Asignaciones de apertura',
                'ordering': ['allocation', 'fuente', 'organismo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_allocationsource_monto_positivo'), models.UniqueConstraint(fields=('allocation', 'fuente', 'organismo'), name='uniq_allocation_fuente_organismo', nulls_distinct=False)],
            },
        ),
        migrations.AddConstraint(
            model_name='distributionversion',
            constraint=models.UniqueConstraint(fields=('gestion', 'numero'), name='uniq_distribution_version_numero'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['gestion', 'version'], name='budget_allo_gestion_6281d0_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['gestion', 'categoria'], name='budget_allo_gestion_a13bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['gestion', 'distrito'], name='budget_allo_gestion_4a40a7_idx'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['gestion', 'estado'], name='budget_rese_gestion_2093a2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserve',
            index=models.Index(fields=['gestion', 'version'], name='budget_rese_gestion_62dc47_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserve',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_reserve_monto_positivo'),
        ),
    ]
