# Generated by Django 6.0.7 on 2026-08-14 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_distributionversion_allocation_reserve_and_more'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.CharField(choices=[('SISPOA_GASTOS_HISTORICO', 'GASTOS histórico (estructura oficial)'), ('SISPOA_GASTOS_ACTUAL', 'GASTOS actual (planilla vigente)'), ('OTRO', 'Otro')], default='SISPOA_GASTOS_ACTUAL', max_length=40)),
                ('filename', models.CharField(blank=True, default='', max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('hoja_seleccionada', models.CharField(blank=True, default='', max_length=200)),
                ('mapeo_json', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('STAGING', 'En staging (sin validar)'), ('VALIDADO', 'Validado (listo para aplicar)'), ('CORREGIDO', 'Corregido'), ('APLICADO', 'Aplicado'), ('RECHAZADO', 'Rechazado')], default='STAGING', max_length=20)),
                ('tipo_importacion', models.CharField(default='GASTOS', help_text='Tipo de contenido de la planilla (GASTOS por ahora).', max_length=20)),
                ('archivo', models.FileField(upload_to='budget/imports/')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_budget', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gestion', models.ForeignKey(help_text='Gestión fiscal a la que se importan las aperturas.', on_delete=django.db.models.deletion.CASCADE, related_name='importaciones_budget', to='gestion.gestionfiscal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de planilla',
                'verbose_name_plural': 'Importaciones de planilla',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fila', models.PositiveIntegerField(help_text='Número de fila real en la hoja (1-based).')),
                ('clasificacion', models.CharField(choices=[('PROGRAM_HEADER', 'Encabezado de programa (P)'), ('SUBPROGRAM_HEADER', 'Encabezado de subprograma (SP)'), ('DETAIL', 'Fila de detalle'), ('SUBTOTAL', 'Subtotal (TS)'), ('TOTAL', 'Total (T)'), ('EMPTY', 'Fila vacía'), ('UNKNOWN', 'No clasificada')], default='DETAIL', max_length=20)),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDO', 'Válido'), ('ERROR', 'Con errores')], default='PENDIENTE', max_length=20)),
                ('errores_json', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='budget.budgetimport')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de importación',
                'verbose_name_plural': 'Detalles de importación',
                'ordering': ['importacion', 'fila'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fila', models.PositiveIntegerField(default=0)),
                ('campo', models.CharField(blank=True, default='', max_length=50)),
                ('valor_original', models.TextField(blank=True, default='')),
                ('valor_normalizado', models.TextField(blank=True, default='')),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('accion', models.CharField(choices=[('REEMPLAZAR', 'Reemplazar valor'), ('NORMALIZAR', 'Normalizar'), ('ASIGNAR', 'Asignar'), ('IGNORAR', 'Ignorar'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=20)),
                ('resuelto', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='budget.importdetalle')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='budget.budgetimport')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error de importación',
                'verbose_name_plural': 'Errores de importación',
                'ordering': ['importacion', 'severidad', 'fila'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetimport',
            index=models.Index(fields=['gestion'], name='budget_budg_gestion_5ed59c_idx'),
        ),
        migrations.AddIndex(
            model_name='importdetalle',
            index=models.Index(fields=['importacion', 'estado'], name='budget_impo_importa_f596cc_idx'),
        ),
        migrations.AddIndex(
            model_name='importerror',
            index=models.Index(fields=['importacion', 'severidad'], name='budget_impo_importa_bf446e_idx'),
        ),
    ]
