# Generated by Django 6.0.7 on 2026-08-15 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budgetimport_importdetalle_importerror_and_more'),
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        ('territorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metodo', models.CharField(choices=[('MANUAL', 'Manual'), ('MONTO_FIJO', 'Monto fijo'), ('PORCENTAJE', 'Porcentaje'), ('POBLACION', 'Población'), ('FORMULA', 'Fórmula')], default='MANUAL', max_length=20)),
                ('bolsa_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Bolsa total (Bs)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('APLICADA', 'Aplicada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(blank=True, help_text='Fuente de la bolsa (sobre la que se reserva).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_territoriales', to='catalogos.fuentefinanciamiento')),
                ('gestion', models.ForeignKey(help_text='Gestión fiscal de la distribución territorial.', on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_territoriales', to='gestion.gestionfiscal')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_territoriales', to='catalogos.organismofinanciador')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Versión de distribución activa al momento de aplicar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_territoriales', to='budget.distributionversion')),
            ],
            options={
                'verbose_name': 'Distribución territorial',
                'verbose_name_plural': 'Distribuciones territoriales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerritorialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poblacion', models.PositiveIntegerField(blank=True, help_text='Población del distrito (método POBLACION).', null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, help_text='Porcentaje del distrito (método PORCENTAJE, escala 0-100).', max_digits=7, null=True)),
                ('monto_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto calculado (Bs)')),
                ('ajuste', models.DecimalField(decimal_places=2, default=0, help_text='Ajuste de redondeo aplicado (monto_final - monto_calculado).', max_digits=18)),
                ('monto_final', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto final (Bs)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_territoriales', to='territorio.distrito')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='budget.territorialdistribution')),
            ],
            options={
                'verbose_name': 'Asignación territorial',
                'verbose_name_plural': 'Asignaciones territoriales',
                'ordering': ['distribucion', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='territorialdistribution',
            index=models.Index(fields=['gestion'], name='budget_terr_gestion_320aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='territorialdistribution',
            constraint=models.CheckConstraint(condition=models.Q(('bolsa_total__gte', 0)), name='check_territorialdistribution_bolsa_positiva'),
        ),
        migrations.AddConstraint(
            model_name='territorialallocation',
            constraint=models.UniqueConstraint(fields=('distribucion', 'distrito'), name='uniq_distribucion_territorial_distrito', nulls_distinct=False),
        ),
    ]
