# Generated by Django 6.0.7 on 2026-08-15 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_territorialdistribution_territorialallocation_and_more'),
        ('catalogos', '0004_blindaje_fuente_oficial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseObjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('allocation', models.ForeignKey(help_text='Apertura programática de la programación.', on_delete=django.db.models.deletion.CASCADE, related_name='objetos_gasto', to='budget.allocation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objeto_gasto', models.ForeignKey(help_text='Objeto del gasto del clasificador (5 dígitos).', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='catalogos.objetogasto')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objeto del gasto programado',
                'verbose_name_plural': 'Objetos del gasto programados',
                'ordering': ['allocation', 'id'],
                'indexes': [models.Index(fields=['allocation', 'objeto_gasto'], name='budget_expe_allocat_523344_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_expenseobjectallocation_monto_positivo'), models.UniqueConstraint(fields=('allocation', 'objeto_gasto'), name='uniq_allocation_objeto_gasto')],
            },
        ),
    ]
