# Generated by Django 6.0.7 on 2026-08-15 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expenseobjectallocation'),
        ('catalogos', '0004_blindaje_fuente_oficial'),
        ('gestion', '0002_alter_gestionfiscal_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TRASPASO', 'Traspaso entre aperturas'), ('INCREMENTO', 'Incremento'), ('DISMINUCION', 'Disminución'), ('NUEVA_APERTURA', 'Nueva apertura'), ('CIERRE_APERTURA', 'Cierre de apertura'), ('CAMBIO_FUENTE', 'Cambio de fuente'), ('AJUSTE_DISTRIBUCION', 'Ajuste de distribución')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('OBSERVADA', 'Observada'), ('APROBADA', 'Aprobada'), ('APLICADA', 'Aplicada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('motivo', models.TextField(blank=True, default='')),
                ('resolucion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reformulaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reformulaciones', to='budget.budgetdocument')),
                ('gestion', models.ForeignKey(help_text='Gestión fiscal de la reformulación.', on_delete=django.db.models.deletion.CASCADE, related_name='reformulaciones', to='gestion.gestionfiscal')),
                ('solicitada_por', models.ForeignKey(help_text='Usuario que solicita la reformulación.', on_delete=django.db.models.deletion.PROTECT, related_name='reformulaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version_origen', models.ForeignKey(blank=True, help_text='Versión de distribución sobre la que opera (la fijada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reforms_origen', to='budget.distributionversion')),
                ('version_resultante', models.ForeignKey(blank=True, help_text='Versión resultante. Fase 10: se deja NULL (la reformulación opera directamente sobre las filas existentes; el histórico queda en ReformMovement + EventoAuditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reforms_resultantes', to='budget.distributionversion')),
            ],
            options={
                'verbose_name': 'Reformulación',
                'verbose_name_plural': 'Reformulaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReformMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TRASPASO', 'Traspaso'), ('INCREMENTO', 'Incremento'), ('DISMINUCION', 'Disminución'), ('CAMBIO_FUENTE', 'Cambio de fuente')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto (Bs)')),
                ('saldo_antes', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo del AllocationSource de origen (destino si INCREMENTO) antes.', max_digits=18, null=True)),
                ('saldo_despues', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo del AllocationSource de origen (destino si INCREMENTO) después.', max_digits=18, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('apertura_destino', models.ForeignKey(blank=True, help_text='Apertura que recibe saldo (TRASPASO/INCREMENTO).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_reform_destino', to='budget.allocation')),
                ('apertura_origen', models.ForeignKey(blank=True, help_text='Apertura que cede saldo (TRASPASO/DISMINUCION/CAMBIO_FUENTE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_reform_origen', to='budget.allocation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuente', models.ForeignKey(blank=True, help_text='Fuente del movimiento (destino para CAMBIO_FUENTE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_reform', to='catalogos.fuentefinanciamiento')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_reform', to='catalogos.organismofinanciador')),
                ('reform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='budget.reform')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de reformulación',
                'verbose_name_plural': 'Movimientos de reformulación',
                'ordering': ['reform', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reform',
            index=models.Index(fields=['gestion'], name='budget_refo_gestion_182cdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='reformmovement',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='check_reformmovement_monto_positivo'),
        ),
    ]
