# Generated by Django 6.0.7 on 2026-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_limpiar_indices_redundantes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expenseobjectallocation',
            name='presupuesto_allocat_c5ae8a_idx',
        ),
    ]
