# Generated by Django 6.0.7 on 2026-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_renombrar_perfiles_importacion_pip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetimport',
            name='perfil',
            field=models.CharField(choices=[('PIP_GASTOS_HISTORICO', 'GASTOS histórico (estructura oficial)'), ('PIP_GASTOS_ACTUAL', 'GASTOS actual (planilla vigente)'), ('OTRO', 'Otro')], default='PIP_GASTOS_ACTUAL', max_length=40),
        ),
    ]
