# Generated by Django 6.0.7 on 2026-08-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_modelos_en_espanol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reforma',
            name='version_resultante',
            field=models.ForeignKey(blank=True, help_text='Versión resultante. Fase 10: se deja NULL (la reformulación opera directamente sobre las filas existentes; el histórico queda en ReformaMovimiento + EventoAuditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reforms_resultantes', to='budget.distribucionversion'),
        ),
        migrations.AlterField(
            model_name='reformamovimiento',
            name='saldo_antes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo del AperturaFuente de origen (destino si INCREMENTO) antes.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='reformamovimiento',
            name='saldo_despues',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo del AperturaFuente de origen (destino si INCREMENTO) después.', max_digits=18, null=True),
        ),
    ]
