# Generated by Django 6.0.7 on 2026-08-19 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_ajustar_referencias_renombradas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apertura',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apertura',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='apertura',
            name='estado_revision',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20, verbose_name='Estado de revisión'),
        ),
        migrations.AddField(
            model_name='apertura',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='apertura',
            name='observado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apertura',
            name='observado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_observadas', to=settings.AUTH_USER_MODEL, verbose_name='Observado por'),
        ),
        migrations.AddField(
            model_name='apertura',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apertura',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
    ]
