# Generated by Django 6.0.7 on 2026-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_revision_por_categoria_programatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprogramaticatecho',
            name='codigo',
            field=models.CharField(max_length=40),
        ),
    ]
