# Generated by Django 6.0.7 on 2026-08-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_subprograma_sin_sp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoProgramaDirectriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gestion', models.PositiveIntegerField(db_index=True, verbose_name='Gestión')),
                ('nivel_entidad', models.CharField(choices=[('MUNICIPAL', 'Gobiernos Autónomos Municipales e IOC'), ('DEPARTAMENTAL', 'Gobiernos Autónomos Departamentales y Regionales'), ('CENTRAL', 'Entidades del nivel central del Estado'), ('UNIVERSIDAD', 'Universidades públicas')], default='MUNICIPAL', max_length=20, verbose_name='Nivel de entidad')),
                ('desde', models.PositiveIntegerField(verbose_name='Programa desde')),
                ('hasta', models.PositiveIntegerField(verbose_name='Programa hasta')),
                ('denominacion', models.CharField(max_length=300, verbose_name='Denominación')),
                ('finalidad_funcion', models.CharField(blank=True, max_length=120, verbose_name='Finalidad y función')),
                ('sector_economico', models.CharField(blank=True, max_length=60, verbose_name='Sector económico')),
                ('normativa', models.CharField(blank=True, max_length=200, verbose_name='Norma de respaldo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rango de programa de la directriz',
                'verbose_name_plural': 'Rangos de programa de la directriz',
                'ordering': ['gestion', 'desde'],
                'constraints': [models.UniqueConstraint(fields=('gestion', 'nivel_entidad', 'desde', 'hasta'), name='rango_directriz_unico'), models.CheckConstraint(condition=models.Q(('hasta__gte', models.F('desde'))), name='rango_directriz_bien_formado')],
            },
        ),
    ]
