# Generated by Django 6.0.7 on 2026-08-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_rango_directriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprogramaticatecho',
            name='rango_directriz',
            field=models.ForeignKey(blank=True, help_text='Solo en el nivel PROGRAMA: el rango del Anexo VI que aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='budget.rangoprogramadirectriz', verbose_name='Rango de la directriz'),
        ),
    ]
