# Generated by Django 6.0.7 on 2026-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_jerarquia_correcta'),
    ]

    operations = [
        migrations.AddField(
            model_name='apertura',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Origen'),
        ),
    ]
